### ISSUE TITLE
Extremely slow behaviour

### ISSUE THREAD

**Issue by vadim-shb** [hsz/idea-gitignore#100]
I have .gitignore file in idea project (https://github.com/vadim-shb/blanky/blob/master/.gitignore). It freeze like a hall when I start typing new line in it (for example: server/target)

When file is empty it works pretty smooth.

.ignore 1.0.2
IDEA 14.1
Debian Linux 8 (jessie)
Hardware is ok(Lots of RAM, CPU-cores, SSD)

**Comment by hsz** [comment]
Please verify if everything is fine with release `v1.1`.

**Comment by vadim-shb** [comment]
It feels much better now. Plugin become usable again. Thanks!
Issue can be closed.

**Comment by hsz** [comment]
Nice to hear. Thanks and good luck !
