### ISSUE TITLE
Add support for .jshintignore

### ISSUE THREAD

**Issue by SimenB** [hsz/idea-gitignore#103]
You can reuse the icon from normal .jshintrc files.

![](https://cloud.githubusercontent.com/assets/1404810/7001309/8e1f5068-dc36-11e4-877c-5f48d9237f20.png)

**Comment by hsz** [comment]
Thanks for the suggestion. I'll implement it with the next release.

**Comment by hsz** [comment]
Introduced with release `v1.1`.

**Comment by SimenB** [comment]
Great, thanks!

**Comment by SimenB** [comment]
@hsz This plugins greys out the ignored files. Is it possible to change that? While I don't want to lint the files, I don't want them greyed out either :smile:

**Comment by hsz** [comment]
@SimenB you can disable ignoring in the plugin settings

**Comment by SimenB** [comment]
Awesome, thanks!

**Comment by SimenB** [comment]
@hsz Where can I find this setting?

**Comment by hsz** [comment]
Hello @SimenB !

It's in <kbd>Settings</kbd> > <kbd>Version Control</kbd> > <kbd>Ignore Files Support</kbd> settings page.
On the bottom you have **Languages settings** panel - you have to find `jshintignore` row and tick the **Enable ignoring** checkbox.
