### ISSUE TITLE
Nested repositories handling regression.

### ISSUE THREAD

**Issue by Grief** [hsz/idea-gitignore#105]
Seems it is related to 'Handling outside ignore rules (.gitignore global file)'.

If you have git repository at /some_dir/repo_a with .gitignore file containing the only line 'repo_b', then
if you have another repository at /some_dir/repo_a/repo_b, all files in repo_b are marked as ignored.

In version 1.0.2 this was working as I expected and only files listed in /some_dir/repo_a/repo_b/.gitgnore were marked as ignored.

**Comment by hsz** [comment]
If you have a project in which project base dir points to the `/some_dir/repo_a/` it's quite natural that it will mark `repo_b` inside it as ignored - isnt' it ?

**Comment by Grief** [comment]
No it isn't. At least since there is another repo in that dir. For example, we have a project which uses a shared component. Both of them are stored in the separate git repositories. Project requires the shared component to be somewhere inside (i.e ./modules/shared_component). 

When I make changes in files inside and outside that dir, IntelliJ is smart enough to understand that files inside that dir don't belong to the project itself but only to the shared component. So when I press commit/push button, it splits changes between these repositories correctly and prepares pushes to both repositories. 

At the same time, .ignore-plugin did the same until the latest update.

I hope it is possible to do one of:
1. leave the previous behavior at least for nested repositories (seems that the added functionality is useful for someone in case of nested directories, not repositories. Otherwise, why was it added?)
2. add an option to disable that path inheritance functionality completely.

**Comment by vsch** [comment]
I am encountering the same issue. I have several sub-modules included in the main project's git. The sub-module directories are sub-directories of the main project but these directories are not included in the main project's git repository. Instead, they are added as sub-modules in IntelliJ under "version control" VCS directory mapping. I have defined these submodule repositories so that IntelliJ handles commits and pushed properly.

All the files in sub-modules show up as ignored even through they are part of VCS operations. Disabling file status coloring in .gitignore plug-in is a simple work-around.

**Comment by CodingAspect** [comment]
+1
Looking forward for a hotfix.

**Comment by hsz** [comment]
Ok, I've made a change that introduces for each module a separated ignore scope. Quick preview below:

*Ignore rules:*

`.gitignore`

    *
    !.gitignore

`Submodule/.gitignore`

    foo.txt


![image](https://cloud.githubusercontent.com/assets/108333/7216755/27eae356-e60a-11e4-8ddd-f3e8d953d824.png)


What do you think ?

**Comment by Cervator** [comment]
Looks good to me and I've also hit this issue and am eager to get my colors back :-)

Thanks for the nice plugin!

**Comment by CodingAspect** [comment]
Thanks hsz for such a quick response. This sounds great.
I hope there won't be any bad impact on existing logic.

**Comment by Grief** [comment]
If it respects intellij's vcs source roots, then it's totally ok for me. Thanks!

**Comment by hsz** [comment]
@Grief 
Ok, I've switched from submodules to VCS roots as you've mentioned - that's better case.

@CodingAspect 
There will be no bad inpact - it's additional feature. I just reset the ignore scope when any sub-VCS root appears in the project.

I'll release it in a few days.

**Comment by hsz** [comment]
Fix has ben released just right now with `v1.1.2`

**Comment by Grief** [comment]
Thanks @hsz ! It works.
