### ISSUE TITLE
Ignored directory with single asterisk is ignore recursively

### ISSUE THREAD

**Issue by jeichhorn** [hsz/idea-gitignore#113]
I have a project with multiple modules and wand to ignore directories with specific names directly below the modules but not recusivly:

.gitignore:
```
*/foo/
```

Project structure:
* `module1/foo/`  <-- Directory should be ignored
* `module1/src/foo/` <-- Directory should not be ignored

This works when using the git command line client, but the IntelliJ .ignore plugin marks the directory `module1/src/foo/`as ignored.

Here is a sample project: https://www.dropbox.com/s/vm83srx3eo0ogqj/gittest.tar.gz?dl=0

**Comment by jeichhorn** [comment]
Only when using double-asterisks, the directory should ignored recursivly:
```
**/foo/
```

**Comment by hsz** [comment]
@jeichhorn Thank you for the report. I'll take care of it soon and push with the next release.

**Comment by hsz** [comment]
@jeichhorn If I'll prepare a RC build, could you spend a moment and test it if everything works fine ?

**Comment by jeichhorn** [comment]
@hsz Sure, just send me the RC build

**Comment by hsz** [comment]
It's available here: https://github.com/hsz/idea-gitignore/releases/tag/v1.1.2-RC

**Comment by jeichhorn** [comment]
A quick check of the v1.1.2-RC looks fine. I'll test it in-depth during the next week.

**Comment by jeichhorn** [comment]
The RC fixes this issue.

**Comment by hsz** [comment]
Fix has ben released just right now with `v1.1.2`
