### ISSUE TITLE
a way to disable recursive .gitignore check

### ISSUE THREAD

**Issue by piotrekkr** [hsz/idea-gitignore#114]
Recently, after updating my .ignore plug-in in PHPStorm I get strange behaviour from .ignore plugin. It always check for every .gitignore file inside my project /vendor/ directory, which is set to be fully ignored. This scanning takes a long time and make my laptop fans spin like crazy. Can I somehow disable checking for .gitignore files inside ignored directory?

I'm using plugin version 1.1.1.

My .gitignore file which is located in project_root/.gitignore:

    ### Symfony template
    # Cache and logs (Symfony2)
    /app/cache/*
    /app/logs/*
    /app/tmp/*
    !app/cache/.gitkeep
    !app/logs/.gitkeep
    !app/tmp/.gitkeep
    
    # Parameters
    /app/config/parameters.yml
    
    # Managed by Composer
    /app/bootstrap.php.cache
    /bin/*
    !bin/console
    !bin/symfony_requirements
    /vendor/
    
    # Assets and user uploads
    /web/bundles/
    /web/uploads/
    /web/js/
    /web/css/
    
    # Composer PHAR
    /composer.phar
    /.idea

**Comment by hsz** [comment]
Fix has ben released just right now with `v1.1.2`
