### ISSUE TITLE
Error: Directory index is already disposed for Project [...]

### ISSUE THREAD

**Issue by mlachance** [hsz/idea-gitignore#120]
Thrown when two project windows were open, reflecting two distinct instances of the project in different directories.

![screen shot 2015-05-06 at 09 47 19](https://cloud.githubusercontent.com/assets/606322/7489248/f0be9714-f3d4-11e4-9c3d-65a02acc63e4.png)

**Comment by hsz** [comment]
Thank you for reporting. The issue has been already reported in #109 and fixed.

It will be pushed with the next release.

**Comment by mlachance** [comment]
Cool. Thanks!

**Comment by hsz** [comment]
Fix has ben released just right now with `v1.1.2`
