### ISSUE TITLE
Post update Unstable IDE - Hangs on Copy operations

### ISSUE THREAD

**Issue by jghankins** [hsz/idea-gitignore#121]
FYI after recently renabling your plugin, and getting the latest update, InteliJ IDEA started hanging on copy operations.  The problem was repeatable, IE select a small line of code from one file, click over to another open file and before I could select and paste, the IDE would hang.  I had problem with 14.1.2 using bundled 1.8 idk as well as 1.6 (OS X  MBP)

As soo as I disabled the plugin, this problem went away.

**Comment by hsz** [comment]
Thank you for reporting. 
I have never met this kind of behaviour.

Are you copying content between ignore files or any file type?

**Comment by hsz** [comment]
@jghankins Can you verify it with the latest `v1.3.3` version ?
