### ISSUE TITLE
Add Ignore Unversioned Files dialog selections to .gitignore

### ISSUE THREAD

**Issue by tukushan** [hsz/idea-gitignore#124]
When specifying files or patterns to ignore in the [Ignore Unversioned Files dialog](https://www.jetbrains.com/idea/help/ignore-unversioned-files.html) the plugin should add those selections to .gitignore.

This request is to implement functionality in the plugin similar to what is requested here: [IDEA-60354](https://youtrack.jetbrains.com/issue/IDEA-60354)

**Comment by kevincam3** [comment]
When I add a file doing this then go to open the gitignore file afterward, PhpStorm hangs and I have to use the task manager to stop it version 2016.1

**Comment by hsz** [comment]
@kevincam3 Can you please describe it more ?

- what OS do you use,
- what is the path to the Git executable (instalation directory),
- what Git path is set int the IDE's options (Settings > VCS > Git) ?

**Comment by kevincam3** [comment]
Problem seems to happen when .gitignore file is open, then add an
unversioned file to PhpStorm ignore, close .gitignore file and try to
reopen it and computer hangs https://goo.gl/TsK6Ux

   - OS = Windows 10
   - Path to Git executable = https://goo.gl/rXts8i
   - Path set in the IDE's options = https://goo.gl/ZzHlYa


On Tue, May 24, 2016 at 3:27 AM, Jakub Chrzanowski <notifications@github.com
> wrote:

> @kevincam3 <https://github.com/kevincam3> Can you please describe it more
> ?
>
>    - what OS do you use,
>    - what is the path to the Git executable (instalation directory),
>    - what Git path is set int the IDE's options (Settings > VCS > Git) ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hsz/idea-gitignore/issues/124#issuecomment-221177866>
>



-- 
Kevin Campbell
TCM Services - Senior Web Designer
Ofc:  (877) 826-0505 x901
Fax:   (877) 826-0508
kevin@tcmsvc.com
http://www.tcmsvc.net

**Comment by hsz** [comment]
@kevincam3 So as far as I understand, you are able to successfully add unversioned files to the gitignore, but the problem appears later ?

**Comment by kevincam3** [comment]
As you can see from the video after adding the file to PhpStorms ignore I
did a search for it in .gitignore but it was not added. Use it as before
but doing what I showed you causes Phpstorm to crash.

On Tue, May 24, 2016 at 3:54 AM, Jakub Chrzanowski <notifications@github.com
> wrote:

> @kevincam3 <https://github.com/kevincam3> So as far as I understand, you
> are able to successfully add unversioned files to the gitignore, but the
> problem appears later ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hsz/idea-gitignore/issues/124#issuecomment-221182136>
>



-- 
Kevin Campbell
TCM Services - Senior Web Designer
Ofc:  (877) 826-0505 x901
Fax:   (877) 826-0508
kevin@tcmsvc.com
http://www.tcmsvc.net

**Comment by hsz** [comment]
Ah, sorry - I didn't notice the video - thanks for that !
In fact I don't handle adding ignore files directly from the VCS tab (it's done by the Git plugin).

With the latest update a notification appears with the suggestion of adding the unversioned files:

![image](https://cloud.githubusercontent.com/assets/108333/15495062/17bb6d14-218e-11e6-9ed6-db9ec4bed47a.png)

**Comment by kevincam3** [comment]
Disabling the plugin and doing the same thing I did in the video doesn't
crash PhpStorm so I can only assume it's the plugin causing the crash.

On Tue, May 24, 2016 at 4:03 AM, Jakub Chrzanowski <notifications@github.com
> wrote:

> Ah, sorry - I didn't notice the video - thanks for that !
> In fact I don't handle adding ignore files directly from the VCS tab (it's
> done by the Git plugin).
>
> With the latest update a notification appears with the suggestion of
> adding the unversioned files:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/108333/15495062/17bb6d14-218e-11e6-9ed6-db9ec4bed47a.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hsz/idea-gitignore/issues/124#issuecomment-221183483>
>



-- 
Kevin Campbell
TCM Services - Senior Web Designer
Ofc:  (877) 826-0505 x901
Fax:   (877) 826-0508
kevin@tcmsvc.com
http://www.tcmsvc.net

**Comment by hsz** [comment]
@kevincam3 ok, Thank you. I'll investigate this issue more for sure. Let's stay in touch!

**Comment by kevincam3** [comment]
Ok, no problem.

On Tue, May 24, 2016 at 4:16 AM, Jakub Chrzanowski <notifications@github.com
> wrote:

> @kevincam3 <https://github.com/kevincam3> ok, Thank you. I'll investigate
> this issue more for sure. Let's stay in touch!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hsz/idea-gitignore/issues/124#issuecomment-221185766>
>



-- 
Kevin Campbell
TCM Services - Senior Web Designer
Ofc:  (877) 826-0505 x901
Fax:   (877) 826-0508
kevin@tcmsvc.com
http://www.tcmsvc.net

**Comment by zar1k** [comment]
Very good!

**Comment by jaredrummler** [comment]
This notification can become annoying. Is there a way to disable it?
