### ISSUE TITLE
Add to 'exclude'

### ISSUE THREAD

**Issue by fuzzyweapon** [hsz/idea-gitignore#133]
The other file that uses .gitignore style syntax is the `exclude` file found in `.git/info/`

This is used for people to add ignores necessary for their local environment but not something that makes sense to commit into say, a team repo.

For instance, I have an intellij plugin for work, but not everyone uses it.  Sadly, the plugin author (I will not name names but it's from a prominent company) decided to create some weird folder in the root of my project and throw an xml file in it instead of doing this in the .idea folder.

It'd be good if we could re-use the functionality we get for .gitignore for exclude.

**Comment by fuzzyweapon** [comment]
This is, obviously, a feature request. :smile_cat:

**Comment by hsz** [comment]
@fuzzyweapon Thank you for this request.

Do you have any proposition, how to present user this file ?

User cannot open it manually from the IDE because whole `.git` directory is hidden.

**Comment by DsXack** [comment]
We can make `.git` directory is not hidden for working with `.git/hooks` and `.git/info/`:
![screenshot at jun 03 12-59-54](https://cloud.githubusercontent.com/assets/683183/7957500/809fb08a-09f0-11e5-87e0-3014d1500aa2.png)

**Comment by hsz** [comment]
@DsXack That's additional work that all of the JetBrains users will have to do.
