### ISSUE TITLE
Add path for directories added through "Add to .gitignore file" menu.

### ISSUE THREAD

**Issue by AlexeyKosov** [hsz/idea-gitignore#141]
Currently if I click "Add to .gitignore file" on, for instance, "vendor" directory, it adds a new line to .gitignore file: "vendor".
But this excludes all directories with that name, not only the one I selected.
So, maybe it would be better to add "/vendor/" (with leading and trailing slash) in this case?

**Comment by hsz** [comment]
It makes sense. It can be changed to always add leading slash.
However trailing slash is useless here.
