### ISSUE TITLE
Please shorten "add to ignore" item text in context menu

### ISSUE THREAD

**Issue by AlexanderBartash** [hsz/idea-gitignore#148]
![desktop 1_154](https://cloud.githubusercontent.com/assets/932153/8326733/c18c8ed4-1a6b-11e5-8f52-d5cdb9a7217c.png)

**Comment by AlexanderBartash** [comment]
That item makes the popup almost twice wider.

**Comment by hsz** [comment]
@AlexanderBartash Thank you for reporting.

Since next release path will have maximum 30 characters and will be shorten with ellipsis.
Screenshot below:

![image](https://cloud.githubusercontent.com/assets/108333/8327224/0c1a12b4-1a67-11e5-99b5-799916056c5b.png)

**Comment by AlexanderBartash** [comment]
Thank you
