### ISSUE TITLE
Add rule from the context menu on top/bottom of the file

### ISSUE THREAD

**Issue by vaclavpavek** [hsz/idea-gitignore#153]
Please add the possibility of setting where the rules from the context menu - at the beginning or end of the file. Ideal for user defined comment like '### Composer template'.

It would also be good to treat a situation where adding 'template' so that they do not mix templates and user-defined rules.

**Comment by hsz** [comment]
Hello @vaclavpavek,

I'm affraid, I don't clearly get this idea. You would be able to insert new rules from templates to the top or end of the file ? How would you to achieve it ?

**Comment by vaclavpavek** [comment]
Hi
the point is to not blend templates (JetBrains, Composer, etc.) with my definition .gitignore rules.

When working manually or define .gitignore context menu (add to ignore ...) on the file.

Therefore I use 2 sections - templates and project / user custom. My choice is writing on top of the file.

I'd love to, if it was set by the plugin where to store the rules from the context menu or by using the Create section 2 comments as

'### Context / templates' = add rule from context menu's top, add a new rule templates bottom
'### Templates / context' = add rule from context menu to bottom, add a new rule templates top

**Comment by hsz** [comment]
@vaclavpavek What about inserting template at the cursor position ?

I think that it would be much more intuitive and flexible.

**Comment by vaclavpavek** [comment]
It should be okay
