### ISSUE TITLE
Gitignore global abuses CPU

### ISSUE THREAD

**Issue by vadviktor** [hsz/idea-gitignore#154]
Hey,

I am using IntelliJ 14.1.4 on Ubuntu 15.04 in VirtualBox 5, running with JRE8 64bit.

When I open a `.gitignore` file AND a `.gitignore_global` file is at place in my `~` folder, the Idea process starts to abuse my CPU. Though I have the more than enough horse power to handle it, this is really annoying.

How can I be of help tracking down the core of the problem?

Thanks in advance!

**Comment by fhorlaville** [comment]
Hi, I am seeing the same behaviour on 1.2 with PHPStorm 10. CPU usage jumps to 100% when a .gitignore file is open in a project. Most noticeable after waking up from sleep.

MacBookPro, El Capitan

Thanks!
