### ISSUE TITLE
OSX template containing `\0` instead of `\r`

### ISSUE THREAD

**Issue by nicoespeon** [hsz/idea-gitignore#155]
Hi there!

I spotted something that might be wrong with the OSX `.gitgnore` template.

Here is the generated file I've got:

```
# Created by .ignore support plugin (hsz.mobi)

### OSX template
.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two \r
Icon

# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk
```

The error lies here:

```
# Icon must end with two \r
Icon
```

Actually, it seems that there're 2 `\0` characters instead of 2 `\r`, which might break things [as I ran into some issues with git-related tools](http://forums.gitup.co/t/unhandled-character-in-gitignore/278).

I'm not sure it was expected so I'm reporting as it looks like an issue.

For comparison, here is the diff with the <http://www.gitignore.io> version (which is on the left):

![capture d ecran 2015-07-30 a 09 05 02](https://cloud.githubusercontent.com/assets/1094774/8977538/54e0039c-369a-11e5-8ffc-0402ba7544c8.png)

Thanks a lot for your useful plugin by the way :+1:

**Comment by hsz** [comment]
@nicoespeon Thank you for the reporting this issue.

In fact I didn't expect any problems with `\0`.
Do we really need `\r` character in the generated file  Or we can just remove all `\r` ?

**Comment by nicoespeon** [comment]
I guess `\r` are here to prevent matching an eventual existing `Icon` file which is not the one from the OS, how unlikely it could be.

I guess the original template is this one: <https://github.com/github/gitignore/blob/master/Global/OSX.gitignore>

But the 2 `\r` of this one are parsed into `\0` somewhere. I'm not sure but that might be related to a57acd46f149218c, which was solving issue #13.

I don't have any clue in mind on how to solve this. But I guess that, pragmatically, having `Icon` without any `\r` may be less likely to cause troubles than `Icon` with `\0` which may break things regarding tools you use. What do you think?

**Comment by hsz** [comment]
Nice catch with this #13 issue. ;-)

I don't see any particular reason to keep `\r` in the generated content for now. The simplest way will be just removing them - for now there were no `\r` anyway.

**Comment by nicoespeon** [comment]
Sounds a legitimate hotfix indeed :+1:

**Comment by hsz** [comment]
I cannot allow `\r\r` to appears in the editor because of #13 regresion (I've just tested it again right now). It can be replaced to `\r\n\r\n` but it won't be the original `Icon\r\r` then so there will be no profit.

**Comment by nicoespeon** [comment]
Yep, I don't see any workaround neither since there can't be `\r\r`. Hence the best solution is removing them as you said :smiley:
