### ISSUE TITLE
syntax: glob is missing for generated .hgignore files

### ISSUE THREAD

**Issue by qzole** [hsz/idea-gitignore#158]
By default .hgignore files are treated as using regex syntax.
The templates generate glob syntax rules.
When generating a .hgignore file, there is no `syntax: glob` at the top, so the generated file is mostly invalid (all the *.extension rules)

My suggestion would be to always put `syntax: glob` at the top of the .hgignore file.

Version used: 1.1.4

**Comment by hsz** [comment]
@qzole Thank you for pointing this out.

I've fixed it and it'll be available with the next release.
