### ISSUE TITLE
(local, lib64) folder on VirtualEnv template

### ISSUE THREAD

**Issue by tarzanjw** [hsz/idea-gitignore#159]
I'm using PyCharm, with ignore plugin installed.

**local folder**

When I create virtualenv, the `local` folder is not ignored from git. I made a check at `.gitignore` file and saw that:

```
### VirtualEnv template
# Virtualenv
# http://iamzed.com/2009/05/07/a-primer-on-virtualenv/
...
Local
...
```
I think that it should be:
```
### VirtualEnv template
# Virtualenv
# http://iamzed.com/2009/05/07/a-primer-on-virtualenv/
...
[Ll]ocal
...
```

**lib64**

I created virtualenv for `python3` by `pyvenv`, the `lib64` (symbolic liked to *lib*) is not ignored in `.gitignore`.

Could anyone make a pull request for this? I am not familiar  with Java.
Thanks,

**Comment by hsz** [comment]
@tarzanjw Thank you for your reporting.

First of all - every template that is available in the `.ignore` plugin are fetched from https://github.com/github/gitignore/ repository. I do not modify them, it's a 3rd party resource - so every suggestion to the templates please report directly to the `github/gitignore` repository.

Second thing - the original `VirtualEnv` template does not contain `Local` entry: https://github.com/github/gitignore/blob/8559c8a381a26e596fc3cf76eeb99df2a62eebf8/Global/VirtualEnv.gitignore
so this *invalid* rule does not come from the plugin resources.

Keep in mind that you can create a pull request for this file in `github/gitignore` project and enhance the `VirtualEnv` rules.

Good luck !
