### ISSUE TITLE
Unchanged files marked as modified

### ISSUE THREAD

**Issue by whitefire** [hsz/idea-gitignore#160]
Hi!

This plugin seems to mark non-project files as modified in some subtle way.
They do not show up in changes-views of in version-control, but "close unmodified" no longer works while the plugin is active.

**Comment by hsz** [comment]
Can you provide more information / screenshots ?

**Comment by whitefire** [comment]
I've had a hard time narrowing it down, but I finally got it now.
If a file is open from a directory which is listed in a .gitignore-file it will appear grayed out like so:

![image](https://cloud.githubusercontent.com/assets/727305/9223722/f3ad4e82-40fc-11e5-80c0-494d17d74c19.png)

The file in question will then not be touched by "close unmodified".

**Comment by hsz** [comment]
IntelliJ also doesn't close files that are ignored with `Version Control > Ignored Files` too - for example:

    .idea/workspace.xml

If you open it (without enabled `.ignore` plugin) it has yellow color. `Close unmodified` action is not perdormed on this file.

What do you think about new feature like `Close ignored` action ?

**Comment by whitefire** [comment]
The plugin is currently disabled, but I was unable to reproduce the behaviour you describe.
I tried first with an entire directory, then with a specific file. All files where closed as expected.

I'm currently running PhpStorm 9.0 btw.

My use of .gitignore-files are very simplistic, so I think I will leave the plugin disabled for now.

"Close unmodified" is unbound by default, and this issue has been present for several months now.
I think you can close this issue, as I find it unlikely that anyone else will experience it.

**Comment by hsz** [comment]
Quick showcase about the IntelliJ behaviour with natively ignored files:

Custom `ignored.txt` ignore rule:
![image](https://cloud.githubusercontent.com/assets/108333/9224331/db6fcdae-4101-11e5-8d51-0f6aae69ff69.png)

IntelliJ marks ignored files with yellow color:
![image](https://cloud.githubusercontent.com/assets/108333/9224361/217d4a6a-4102-11e5-8c5f-6dee1f639e55.png)

Closing unbodified files leaves `ignored.txt` opened
![image](https://cloud.githubusercontent.com/assets/108333/9224378/41dcb426-4102-11e5-952d-60ba1a9949a7.png)
![image](https://cloud.githubusercontent.com/assets/108333/9224389/4b042dc2-4102-11e5-8948-4f384d8d7cce.png)

So without breaking IntelliJ logic I can provide extra `Close Ignored` option which will close all grayed files.

**Comment by whitefire** [comment]
If it is a setting that could be enabled it would definitely work for me! :)

**Comment by hsz** [comment]
Ok, feature will be available with the next release. Sneak peek:

![image](https://cloud.githubusercontent.com/assets/108333/9225266/b85bb222-4108-11e5-82c6-e0c18b939909.png)

**Comment by whitefire** [comment]
Thanks! :)
