### ISSUE TITLE
.cfignore not supported

### ISSUE THREAD

**Issue by jchesterpivotal** [hsz/idea-gitignore#161]
The [Cloud Foundry CLI](https://github.com/cloudfoundry/cli) recognises a [`.cfignore` file](https://docs.cloudfoundry.org/devguide/deploy-apps/prepare-to-deploy.html#exclude), which closely resembles a `.gitignore`.

I don't have a PR to hand, just logging this as an act of wishful thinking.

**Comment by hsz** [comment]
@jchesterpivotal  Thank you for reporting.
Feature will be available in release `v1.3`.
