### ISSUE TITLE
IgnoreSettings settings must produce stable state

### ISSUE THREAD

**Issue by develar** [hsz/idea-gitignore#162]
IgnoreSettings has default roaming type, and, so, shared. It is ok.

But IgnoreSettings. getState implemented incorrectly — changed very often https://github.com/develar/__intellij_settings/commits/master/%24APP_CONFIG%24/ignore.xml because HashMap used. Data must be sorted.

**Comment by hsz** [comment]
@develar Thank you for reporting. Indeed it can be very annoying - I didn't notice it before since all my local settings are ignored.

I think that simple migration to `TreeMap` will do the job. I'll fix it with next release.

**Comment by develar** [comment]
Thanks. Currently, I don't use plugin, but I am JetBrains employee and our users complains about it.
