### ISSUE TITLE
Duplicate rules when you add through the wizard

### ISSUE THREAD

**Issue by BorzdeG** [hsz/idea-gitignore#164]
for example, if you add templates "Linux template" and "Vim template", it will be a duplicate of the rules "*~"

**Comment by hsz** [comment]
That's a normal behaviour for now - you are using different templates which are not related with each other.

That gave me a nice idea for extending <kbd>Generate</kbd> button in the Generate Dialog with extra option: `Generate without duplicates`:

![image](https://cloud.githubusercontent.com/assets/108333/9522276/44c716f8-4cd4-11e5-88a7-dee3b593a34b.png)

![image](https://cloud.githubusercontent.com/assets/108333/9522289/51d1773a-4cd4-11e5-82b6-5375e98e01af.png)

**Comment by BorzdeG** [comment]
Yes, it is about this functionality, I had in mind - removing duplicates

**Comment by BorzdeG** [comment]
Just add support for "mnemonics" in the button to be able to type by pressing "Alt+e" to open the menu button. In analogy, as in the VCS-dialog "Commit Changes" button "Commit" through "Alt+i"

**Comment by hsz** [comment]
@BorzdeG Feature will be available in release `v1.3`.
