### ISSUE TITLE
"Unclosed character class" warning is wrong

### ISSUE THREAD

**Issue by mnpenner** [hsz/idea-gitignore#166]
![image](https://cloud.githubusercontent.com/assets/1112998/9883538/8206fe60-5b8f-11e5-9149-9bead5fe335a.png)

`(?<![^/])\.` is a [valid regular expression](https://regex101.com/r/cR8cV8/2). There's clearly a closing `]` :)

**Comment by hsz** [comment]
@mnpenner  Thank you for reporting.
Fix will be available in release `v1.3`.
