### ISSUE TITLE
Ignoring all subdirectories grays out regular files too.

### ISSUE THREAD

**Issue by ekevoo** [hsz/idea-gitignore#167]
I have a very simple project that, when run, creates several subdirectories that are not meant to be versioned. Thus, I added `/*/` to `.gitignore`. Everything (commits, status, diff) works as I expect.

Expect that now the Project tree will grey out all files, not only the folders. [Screenshot.](https://cloud.githubusercontent.com/assets/871714/9971375/5e0ae3a4-5e29-11e5-81f3-3dded378957b.png)

**Comment by hsz** [comment]
@ekevoo Thank you for the bug report.
In fact `/*/` rule adds everything to the ignore list. Your commits, etc works because you have added them to the repository before.

Graying ouy everything with `/*/` is an expected behaviour and cannot be treated as a bug. Sorry.

**Comment by ekevoo** [comment]
That is not true.
![screen shot 2015-11-10 at 08 41 29](https://cloud.githubusercontent.com/assets/871714/11063797/fd9c271c-8786-11e5-8d6a-990e984cf713.png)
