### ISSUE TITLE
Plugin prevents PhpStorm from updating project tree on git branch change

### ISSUE THREAD

**Issue by ewesseloh** [hsz/idea-gitignore#169]
When checking out a git branch with a different set of folders, the project tree will have missing entries and previous entries won't be removed but will have no caption. Operations on those empty items may cause exceptions and PhpStorm to crash.

**before change**:
![before change](https://cloud.githubusercontent.com/assets/14919715/10214103/440ad11c-6815-11e5-9eb4-1933836f13e7.jpg)

**after change**:
![after change](https://cloud.githubusercontent.com/assets/14919715/10214111/4ecda728-6815-11e5-9ae3-18ff9776821a.jpg)

Common items stay as they are.

The problem disappears if you disable the .ignore plugin.

**Comment by hsz** [comment]
@ewesseloh  Thanks for the issue reporting.
Can you confirm that you can still reproduce this issue ?

**Comment by ewesseloh** [comment]
Yes. Even with 2016.1.
Am 20.03.2016 23:59 schrieb "Jakub Chrzanowski" <notifications@github.com>:

**Comment by hsz** [comment]
Can you verify if this bug appears with the following build ? 

https://github.com/hsz/idea-gitignore/releases/tag/v1.2.1-testing

It's a pre-release of 1.3 version and probably it was already fixed. I'm asking you because I cannot longer reproduce it.

**Comment by hsz** [comment]
@ewesseloh please verify this issue with the latest v1. 3.3 version.

**Comment by ewesseloh** [comment]
@hsz since then I did not use that plugin, Today I have updated it and retested, it seems that this bug is gone now, at least at first glance.

Thank you very much!
