### ISSUE TITLE
Consumes high CPU within project of 200k files.

### ISSUE THREAD

**Issue by chmarr** [hsz/idea-gitignore#171]
Hi there! I'm using (well, was using) the .ignore plugin within PyCharm for a large project. When viewing the .gitignore file the CPU usage of my computer skyrockets until I close the .gitignore file. another file deeper in the tree is viewable just fine. If I empty the .gitignore file, so its blank, also no problem. Adding in a single line to the top-level .gitignore file resumes the high CPU usage.

Pertinent facts:
* Project has 200,000 files
* It's primarily a Scala/Java project, with a bit of python that I'm working on.
* Plugin version 1.2
* PyCharm version 4.5

**Comment by adragos** [comment]
I have a similar problem with IntelliJ Idea 15 EAP Ultimate on MacOS 10.11.1
If the .gitignore file is open, CPU usage increases and all gets back to normal if I close the .gitignore file

> IntelliJ IDEA (Minerva) IU-143.870.1
> Build #IU-143.870, built on November 18, 2015
> JRE: 1.8.0_40-release-b92 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by hsz** [comment]
@chmarr @adragos  Thank you for reporting.

I'll merge this issue with #154 as a duplicate.
