### ISSUE TITLE
File status highlight stopped working with PhpStorm 10

### ISSUE THREAD

**Issue by debo** [hsz/idea-gitignore#173]
Hey there, as per subject the file status highlight feature seems to have problem with PhpStorm 10, I recently updated and noticed that neither files nor folder are getting highlighted as expected. Anyone else experienced the problem or know how to solve it? Thanks a lot for your help.

**Comment by hsz** [comment]
@debo Thank you for reporting. Issue will be handled with #174 

Please refer to it and try to apply my possible fix scenario to help me investigating this problem.
