### ISSUE TITLE
ignored files are no longer being colored correctly in Intellij IDEA 15

### ISSUE THREAD

**Issue by laurentdutheil** [hsz/idea-gitignore#174]
Ignored files are no longer being colored correctly in Intellij IDEA 15
For exemple in the screenshot, bower_components is in my .gitignore, but the color is unchanged.

<img width="335" alt="capture d ecran 2015-11-05 a 13 50 19" src="https://cloud.githubusercontent.com/assets/467273/10968811/39102922-83c4-11e5-9c7c-4211ff92a903.png">

**Comment by andsol** [comment]
PhpStorm 10 same issue

**Comment by hsz** [comment]
@laurentdutheil @andsol Thank you for your report.

Can you check if following scenario will fix this problem ?

1. Open `.gitignore` file
2. Remove all rules and press `Ctrl + S`
3. Undo remove and press `Ctrl + S` again

**Comment by laurentdutheil** [comment]
Yes !
This fix the problem

**Comment by vernsix** [comment]
I am having this precise problem with .hgignore files as well.

**Comment by andyfleming** [comment]
@hsz's instructions worked for me as well.

**Comment by gefilte** [comment]
@hsz's instructions did not work for me in Android Studio 1.5.1. Bug persists.

**Comment by JorisDebonnet** [comment]
I also had this issue in PhpStorm 10 (.gitignore), but the workaround works. Disabling and re-enabling the plugin brings back the issue though, but I suppose that is to be expected.

**Comment by tomgrossman** [comment]
The issue reproduce with the new Wbestorm 2016.1 on Ubuntu 14.1.
ignored folders are not grayed out.
Tried the fix above and it didn't work.

**Comment by hsz** [comment]
@tomgrossman What version of plugin do you use ?

**Comment by tomgrossman** [comment]
@hsz latest - 1.2

**Comment by hsz** [comment]
@tomgrossman Fix has been prepared and will be released with the next version.

**Comment by hsz** [comment]
Can you confirm that this issue has been fixed?

**Comment by JorisDebonnet** [comment]
It's fixed for me, at least!

**Comment by tomgrossman** [comment]
@hsz I don't see any update to the plugin :|

**Comment by JorisDebonnet** [comment]
@tomgrossman That's strange, I automatically got 1.3.3 which was released only yesteday. I suggest removing it and adding it back!

**Comment by tomgrossman** [comment]
@hsz @JorisDebonnet Yea, I don't know what was the issue (maybe Webstorm bug) but now I got it and it's fixed! thanks!

**Comment by poseidon0206** [comment]
> @laurentdutheil @andsol Thank you for your report.
> 
> Can you check if following scenario will fix this problem ?
> 
> 1. Open `.gitignore` file
> 2. Remove all rules and press `Ctrl + S`
> 3. Undo remove and press `Ctrl + S` again

I can confirm this works. It's funny how I only bump into this problem 5 years later haha.

**Comment by ahlgreno** [comment]
I'm having this issue for one of my projects (working on other projects) for PyCharm 2022.3.1 , tried the above and it didn't work.

Are there any other project level setting that effect file coloration? 'Version Control > File Status Colors' looks right.
