### ISSUE TITLE
Node-Template: node_modules produces warnings

### ISSUE THREAD

**Issue by dploeger** [hsz/idea-gitignore#176]
If you created a .gitignore from the node template, the following warnings are shown, when inspecting code in IntelliJ:

Warning:(4, 1) '*.log' is covered by 'node_modules'
Warning:(16, 1) 'coverage' is covered by 'node_modules'

Clearly, "*.log" is NOT covered by "node_modules", just as "coverage" isn't.

**Comment by hsz** [comment]
@dploeger Thank you for reporting.

If there is in `node_modules` directory any of the file that is matched by `*.log` or `coverage` rules - and they appear only in this directory - they are treated as "subrules" that can be reduced.

If you'll create some other `*.log` file outside the `node_modules` - this rule will notice it and will not be *covered* by `node_modules`

**Comment by dploeger** [comment]
Sorry for the delay.

Yes, thank you. I didn't notice that.
