### ISSUE TITLE
ignored files are no longer being colored correctly in PhpStorm

### ISSUE THREAD

**Issue by vernsix** [hsz/idea-gitignore#177]
Files and Directories listed in .hgignore file, are not be colored correctly.  Using .gitignore, this works as expected, but not with Mercurial .hgignore.

**Comment by hsz** [comment]
@vernsix Thank you for reporting. Do you have in settings `enable ignoring` checked in `Mercurial` row ?

![image](https://cloud.githubusercontent.com/assets/108333/11280152/d2503646-8ef4-11e5-8bd9-a9ebd3db32c1.png)

**Comment by hsz** [comment]
Duplicate of #174
