### ISSUE TITLE
Incorrect Config With Composer

### ISSUE THREAD

**Issue by julien731** [hsz/idea-gitignore#179]
When generating the ignore rules for Composer, an incorrect format is used. The vendor directory added is written `vendor/`, which causes other vendors directories to be ignored. The correct format to use is `/vendor/`, which would only ignore the root `vendor` directory.

**Comment by hsz** [comment]
@julien731  Thank you for reporting.

This issue is not related to the `idea-gitignore` plugin. All of the templates are fetched from the [github/gitignore](http://github.com/github/gitignore) repository.

**Comment by julien731** [comment]
Sorry about that, and thanks for pointing me in the right direction. I'll try to submit a PR for that.

**Comment by julien731** [comment]
Just for reference, this issue has been addressed here: https://github.com/github/gitignore/pull/1773
