### ISSUE TITLE
Matching patterns in subdirectories not greyed out

### ISSUE THREAD

**Issue by benedictleejh** [hsz/idea-gitignore#180]
For example if the `.gitignore` contains:

```
build/
```

Directory structure:

```
project
\---build/
\---sub
    \---build/
\---.gitignore
```

`project/build/` will be greyed out, but `project/sub/build/` will not, even though `project/sub/build/` is correctly detected as ignored.

**Comment by hsz** [comment]
@benedictleejh  Thank you for reporting. Does this issue appear in the IntelliJ 15 ?

**Comment by benedictleejh** [comment]
Yes, I'm using idea-gitignore with IntelliJ 15.

**Comment by hsz** [comment]
This issue has been already discussed in #174 
I've suggested a walkaround in the third post which you can apply.

Anyway the issue is still open and waits for the fix.

Thanks again for your time and have a happy coding !
