### ISSUE TITLE
Add support for .gitattributes

### ISSUE THREAD

**Issue by kaltokri** [hsz/idea-gitignore#182]
Hi,

it would be great if you can add support for .gitattributes files, too.

Kind regards
Rolf

**Comment by hsz** [comment]
@kaltokri Sorry, but `gitattributes` support is out of the plugin's scope and it will not be supported.

The syntax and purpose are slightly different. It simply doesn't match the context of the `.ignore` plugin.

**Comment by jschilling1** [comment]
+1

**Comment by Geolim4** [comment]
I agree, there's no plugin actually that support .gitattributes files.
You could be the first one that integrate it's support.

It's up to your decision, hope you'll change your mind @hsz ;)

Cheers,
Georges
