### ISSUE TITLE
.gitignore sorted wrong in the project files view

### ISSUE THREAD

**Issue by jschilling1** [hsz/idea-gitignore#183]
With the "gitignore" plugin enabled PyCharm doesn't sort the .gitignore file properly alongside .gitattributes as shown. With the plugin disabled .gitignore appears next to .giattributes as one would expect.
![screenshot from 2015-12-18 11 26 16](https://cloud.githubusercontent.com/assets/12403565/11901614/82a96a12-a57a-11e5-926a-fe85b1665448.png)

**Comment by hsz** [comment]
@jschilling1 Thank you for reporting it.

I've installed the latest *PyCharm Community Edition 5.0.2* and with **disabled .ignore** plugin the project tree looks like:

![image](https://cloud.githubusercontent.com/assets/108333/11974779/9aabd74e-a967-11e5-89b3-55ad13397a28.png)

When I **enabled .ignore** it looks in the same way:

![image](https://cloud.githubusercontent.com/assets/108333/11974787/bed541aa-a967-11e5-88b9-f23fc0bcd04d.png)

Plugin itself doesn't mess with the project structure - it changes only the status of the files to *ignored* or leaves the default one - but it doesn't affect the tree in other way than the color.

**Comment by jschilling1** [comment]
it looks like the reason for this is that i had "Sort by type" enabled in the project view and the type of .gitignore file with the plug-in enabled is not the same as that of .gitattributes. i suppose there is no way to have the fancy icon next to .gitignore and not change its type?
![screenshot from 2015-12-23 10 19 12](https://cloud.githubusercontent.com/assets/12403565/11979533/1ab42a5a-a962-11e5-816b-28c834555b82.png)

**Comment by hsz** [comment]
@jschilling1 To have an icon assigned to the file (files extension like `.txt` or in this case `.gitignore`) you have to bind it to the plugin. If the plugin is called `.ignore` - it will be on the top of the list.
If it will be called `xyz` - it will move to the bottom.

I cannot rename the plugin to change the behaviour of the files sorting. ;-)
