### ISSUE TITLE
More files being ignored than should be

### ISSUE THREAD

**Issue by johnhall** [hsz/idea-gitignore#192]
Hi,

I'm running a gradle build environment and it has a buildSrc directory.  In this directory, I need to ignore the .gradle and build directories and all their contents.  The pertinent entries in the .gitignore are:

/.idea
/build
/**/*.iml
/.gradle
/buildSrc/.gradle
/buildSrc/build

However, this is resulting in the build.gradle and all contents of the src directory being ignored as well, which puts me in a position where I have to manage my file changes with Git outside of IntelliJ.

**Comment by hsz** [comment]
@johnhall What version of plugin do you use ? Can you still reproduce this issue ?

**Comment by johnhall** [comment]
Yes, it's consistently reproducible.  I'm using version 1.2 on IntelliJ 15.0.4.

**Comment by hsz** [comment]
Can you provide me some fake-project with the files tree and gitignore file that is simmilar to your environment and will reproduce the issue ?

**Comment by johnhall** [comment]
Sure, but I'm beginning to wonder if it might be IntelliJ itself that is causing the issue.  Check out this graphic:

![image](https://cloud.githubusercontent.com/assets/1751577/13884102/0f04c452-ecf2-11e5-80ac-bee6a7281f36.png)

I had a typo, so renamed playGround.html to playground.html.  Notice how it's displayed incorrectly as playGround.html in the Version Control panel, but is displayed correctly as playground.html in the editor tab and the editor tab does not see the file as new (the text isn't green).  Since the file name is out of sync, playground.html is intermittently dropped from the change set list in the Version Control panel (I think); I have to refresh the panel to get it to show up again.  Also, playgroundFormCtrl.js is recognized as not added to Git in the project panel and editor tab, but is recognized as added in the Version Control panel.

Is it possible that IntelliJ could be causing issues for your plugin like this?

**Comment by johnhall** [comment]
At this point I think that this issue was actually caused by IntelliJ itself.  Sorry to bother you with this.

**Comment by hsz** [comment]
@johnhall I appreciate that you had the time and willingness to improve the quality of my plugin, thanks ! :+1:
