### ISSUE TITLE
Add P4ENVIRO variable support

### ISSUE THREAD

**Issue by zielu** [hsz/idea-gitignore#200]
Hi, 
 I use P4ENVIRO variable to keep common settings (user, pass, port) in one place so my P4CONFIG file contains only P4CLIENT entry. To use the plugin now I must create one file containing content from both of them.

For reference:
https://www.perforce.com/perforce/doc.current/manuals/cmdref/P4ENVIRO.html

**Comment by hsz** [comment]
@zielu Thanks for this suggesstion, but `.ignore` plugin is supposed to handle only `ignore`-type files.
It will not cover any other cases not related to the VCS exclusion.

**Comment by zielu** [comment]
Hi, my case has nothing to do with ignore files (for P4IGNORE I do use .ignore plugin).

Maybe more info will help :) - I use perforce with 2 environment variables P4ENVIRO and P4CONFIG (technically 3 for ignores) and files contain data that I described earlier.

My issue is that 'Relative P4CONFIG file' option only allows me to specify my stripped-down P4CONFIG file name. My suggestion is to add another input for path to P4ENVIRO file and use them both during properties resolution.
