### ISSUE TITLE
Immense X server CPU usage on Ubuntu 14.04 when "global ignores" pane is open in PhpStorm

### ISSUE THREAD

**Issue by rask** [hsz/idea-gitignore#201]
I'm running on Ubuntu 14.04 LTS (64-bit) and a new laptop with an 8-core i7, 16GB RAM and a laptop Radeon R7 370M GPU. The GPU uses a proprietary driver (`fglrx`).

When I use a global `.gitignore` file (defined in `.gitconfig`) and open a `.gitignore` file inside PhpStorm (which then displays the globally ignored rules in a "Outer ignore rules" pane at the bottom of the window) the Linux X server CPU usage jumps to 100%+ constant and does not come down until some other file is opened in PhpStorm (essentially hiding the global ignores pane). X server is the workhorse which drives the operating system GUI and input.

Suggested steps to reproduce:

1. Install PhpStorm (my version is 10.0.3 at the time of writing)
2. Install the .ignore plugin
3. Create a global .gitignore file and use it in `~/user/.gitconfig` (and add some lines to be thorough)
4. Open a project in PhpStorm
5. Create a project specific .gitignore file and open said file while the .ignore plugin is active
6. The minipane with global ignores listed should appear in the bottom of the window

**If** this is not restricted to my system **and** your hardware is responsive then your CPU fans should start spinning immensely right about now.

I'm not sure whether this happens in other JetBrains products too. I'm also not certain whether this issue stems from PhpStorm, .ignore, X or something else on my system.

Let me know if you need additional information.

**Comment by hsz** [comment]
@rask Thank you for reporting and nice description.

I'll mark it as a dupluicate of #154 and close - but it'll help me for sure with the debugging !

**Comment by rask** [comment]
Didn't spot that issue as I was searching for X server related problems. Let me know if you need some testing help later on. :)
