### ISSUE TITLE
Indexing horribly slow

### ISSUE THREAD

**Issue by mkrumpholz** [hsz/idea-gitignore#210]
Every time i update to a newer EAP build the index is rebuilt and guess what, the .ignore indexing takes the most time of it. This time i'm already waiting 20 mins and it's still running... :( It slows down IDEA until finished. This is not a new problem of the current version(s), i have seen this since i started using the plugin.

**Comment by lebedevsky** [comment]
Same problem, but it came after last updating. it slow phpstorm and run in background tasks.

**Comment by hsz** [comment]
@mkrumpholz @lebedevsky Thanks for reporting this issue. It has already been reported in #204 
I'll close this one - please keep an eye on the above thread, thanks !

**Comment by zippy1981** [comment]
I had this issue today with .ignore 1.5 on PHPStorm 20016.1.2. Removing it fixed this issue.
