### ISSUE TITLE
User Templates

### ISSUE THREAD

**Issue by kevincam3** [hsz/idea-gitignore#212]
After upgrading to the latest version (1.3.3), I don't see the option in PhpStorm's settings to add custom user templates.

**Comment by hsz** [comment]
Thank you for reporting this issue. You can add new user's template in the settings:

<kbd>Settings</kbd> > <kbd>Version Control</kbd> > <kbd>Ignore Files Support</kbd> > User templates section > **Add button**

![image](https://cloud.githubusercontent.com/assets/108333/14273977/dbfeecba-fb0e-11e5-84e0-3df2e65a627a.png)

**Comment by kevincam3** [comment]
Got it, Thanks.

On Tue, Apr 5, 2016 at 4:15 AM, Jakub Chrzanowski <notifications@github.com>
wrote:

> Thank you for reporting this issue. You can add new user's template in the
> settings:
>
> Settings > Version Control > Ignore Files Support > User templates
> section > *Add button*
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/108333/14273977/dbfeecba-fb0e-11e5-84e0-3df2e65a627a.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hsz/idea-gitignore/issues/212#issuecomment-205690799>
>



-- 
Kevin Campbell
TCM Services - Senior Web Designer
Ofc:  (877) 826-0505 x901
Fax:   (877) 826-0508
kevin@tcmsvc.com
http://www.tcmsvc.net
