### ISSUE TITLE
"Entry never used" is wrong

### ISSUE THREAD

**Issue by mnpenner** [hsz/idea-gitignore#213]
![screenshot from 2016-04-05 10-40-25](https://cloud.githubusercontent.com/assets/1112998/14292077/49c3235e-fb1b-11e5-87da-2cccec7a6cab.png)

I think your regex parser is struggling with the negative look-behind. I definitely have some dot files in my project, and I can see that the regex is successfully ignoring them.

```regex
(?<![^/])\.
```

This regex says: "periods not preceded by something other than a forward slash".

**Comment by hsz** [comment]
@mnpenner  Thanks for reporting. The problem was that I've tested entries with `match()` instead of `find()` - since Mercurial matches entries even with partial regexp it wasn't working.

Fix will be available in the next release.
