### ISSUE TITLE
tricky ignore rules won't apply to project view

### ISSUE THREAD

**Issue by manu09** [hsz/idea-gitignore#214]
The only unignored folder in `wp-content` is my own theme (last line). All the other folders (languages, plugins, other themes, ...) and files in there still show as if they would be tracked, which is not the case. I expect them to have the same gray color as ignored items would have (like `wp-includes`, `wp-admin`).

![2016-04-06-201452_1280x800_scrot](https://cloud.githubusercontent.com/assets/1057526/14327773/0e8e89ee-fc34-11e5-856e-ba33eb70b35d.png)

Atom editor is doing it right:

![2016-04-06-202415_1280x800_scrot](https://cloud.githubusercontent.com/assets/1057526/14328077/74377d54-fc35-11e5-878c-b65be6df659a.png)

I don't feel like this is a dup of #174, I'm using PhpStorm 2016.1 with v1.3.3.

**Comment by hsz** [comment]
@manu09 
Thanks for reporting. I've fixed it with 7fe65e2 and it will be available in the next release.
