### ISSUE TITLE
Please add JetPack ignore

### ISSUE THREAD

**Issue by bbuhler** [hsz/idea-gitignore#215]
It is more or less a clone of gitignore...
See https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#Using_.jpmignore_to_ignore_files

With an monochrom version of this icon:

![Jetpack Logo](https://wiki.mozilla.org/images/thumb/3/3d/Jetpackicon.png/100px-Jetpackicon.png)

**Comment by hsz** [comment]
@bbuhler Thanks for the suggestion. I've implemented it and it'll be available in the next release.
