### ISSUE TITLE
"Add to .gitignore" adds entries to random line

### ISSUE THREAD

**Issue by bluemoehre** [hsz/idea-gitignore#216]
Currently it is not possible to keep a nice/structured `.gitignore` (see [gitignore-collection](https://github.com/github/gitignore/blob/master/Symfony.gitignore)) because the context menu option **add to .gitignore** adds new lines randomly or to last cursor position (when file was already opened somewhen).
I suggest to always append. Then it will be possible to manually add a comment block as separator at the end of the file like ...

    # 
    # here follows unsorted stuff
    #

**Comment by hsz** [comment]
@bluemoehre Thank you for this suggestion. It's a really interesting feature - I'll try to provide somthing like that in the future releases.
