### ISSUE TITLE
Subfolders recognizion

### ISSUE THREAD

**Issue by umbertix** [hsz/idea-gitignore#218]
I'm not 100% sure that this is actually a bug but I will expose it and just open a bit of discussion maybe.

I just found that when you define subfolders to be ignored but you don't especifically say it. It doesn't represent correctly the ignored files , check the image for example [image](http://postimg.org/image/5vzo2j0af/).

But if you actually specify it  with the * then it's fine. 
[image](http://postimg.org/image/7edlrab7b/).

In both images I'm refering to line 9.

**Comment by hsz** [comment]
@umbertix Thanks for reporting - it was indeed a bug. The fix will be available in the next release.
