### ISSUE TITLE
problem with ignored untracked files - not all files "gray"

### ISSUE THREAD

**Issue by BorzdeG** [hsz/idea-gitignore#219]
YouTrack issue: https://youtrack.jetbrains.com/issue/IDEA-155001

**Comment by maksymcherevko** [comment]
Have same issue with this...
![screenshot_114](https://cloud.githubusercontent.com/assets/16465396/15011126/c32a409e-11f8-11e6-935d-c2307ff58459.png)

**Comment by tarzanjw** [comment]
It also occurs for this pattern:

Suppose that I added `[Ii]clude` to .gitignore file, the `include` directory was not gray. It was only gray when I added `include` directly into .gitignore file.

**Comment by hsz** [comment]
@BorzdeG @maksymcherevko Thank you for reporting - it's fixed and will be available in the next release!

@tarzanjw It was quite different issue.. Anyway fixed too, thanks :+1:
