### ISSUE TITLE
Valid email not recognised in authors' email field

### ISSUE THREAD

**Issue by endelwar** [hsz/idea-gitignore#224]
If authors email has a domain extension longer than 4 chars or contains non-ascii chars is marked as invalid.

Valid domain extension includes p.e. ".agency", ".travel", ".みんな" and others; a not complete list is available here https://newgtlds.icann.org/en/program-status/delegated-strings

**Comment by hsz** [comment]
@endelwar Are you sure that you've reported this issue in the correct place ?

**Comment by endelwar** [comment]
You're right... wrong repository, sorry :)
