### ISSUE TITLE
"is covered by" is wrong

### ISSUE THREAD

**Issue by mnpenner** [hsz/idea-gitignore#228]
Running version 1.4.1 now.

This warning is giving false positives:

![image](https://cloud.githubusercontent.com/assets/1112998/15512599/9914f996-2195-11e6-9d78-6cdb56000288.png)

`~$` is _not_ covered by `(?<![^/])\.` nor `^node_modules/`.

Most of those "entry is never used" warnings are wrong too actually.

**Comment by jwfearn** [comment]
Here's another one I found:
![image](https://cloud.githubusercontent.com/assets/276996/15681495/3e9cd6ea-270e-11e6-824f-fbe3d2bc1422.png)

**Comment by hsz** [comment]
@mnpenner @jwfearn 

Those rules are marked as covered because the rule that is marked as covering those subrules.

For example `~$` matches some files that ends with `~` character but they are located under the `node_modules` directory and nowhere else.

If you'll create some template `foo~` file in the root directory - it will not be matched as covered by `^node_modules/` directory.

Can you please verify it ?

**Comment by mnpenner** [comment]
I created a new file called `derp~` inside the root of my project directory, and that warning did indeed go away. However, I then moved the file into another ignored directory, and the warning did not re-appear to tell me it was covered by the other directory. Lastly, I removed `^node_modules/` and `~$` from my .hignore and then did `hg st | grep '~'` to see what files were being covered, and there does not appear to be any `~` files in my `node_modules` directory. `find . -name *~` only finds my one `derp~` file too, so I don't think I have any other `~` files. If that's the case, how can `^node_modules/` be covering it?

**Comment by Alexsey** [comment]
![screen shot 2017-06-19 at 20 25 20](https://user-images.githubusercontent.com/6392013/27297422-77f9bedc-552d-11e7-9e39-8323036ea980.png)

**Comment by hsz** [comment]
Can I ask you to check if this issue is still present in v2.1.1?

**Comment by Alexsey** [comment]
<img width="984" alt="screen shot 2017-08-24 at 14 25 35" src="https://user-images.githubusercontent.com/6392013/29664452-485e7b7a-88d8-11e7-99df-3c304132fadc.png">
<img width="366" alt="screen shot 2017-08-24 at 14 25 59" src="https://user-images.githubusercontent.com/6392013/29664454-49ffb976-88d8-11e7-80ab-82c91ea16173.png">

**Comment by mnpenner** [comment]
I don't seem to have any "is covered by" warnings anymore, but I have a lot of incorrect "entry is never used" warnings, which I've verified by removing the line and running `hg stat` again. The number of untracked files changes, so these rules are definitely doing something.

**Comment by cwilli34** [comment]
Every single line for me says "entry is never used."  This is in Rider 2017.2 EAP.  My .gitignore file is in the root of my project.  My project structure looks like:

|-- .git
|-- Help
|-- src
-- .gitattributes
-- .gitignore
-- Docs.shfbproj
-- README.md

I used direct paths to some directories and files, so there really is no reason for it.

**Comment by toolforger** [comment]
@mnpenner `find . -name *~` does not do what you think it does, because the `*~` will be interpreted by the shell, not by `find`.
You should say `find . -name "*~"` instead.

**Comment by mnpenner** [comment]
@toolforger Thanks. That does indeed turn up a whole bunch of files under `node_modules` but it doesn't explain why this plugin thinks the `~$` rule is unused. Adding and removing that line from `.hgignore` changes the output of `hg stat`, so one way or another, it's used.

**Comment by hsz** [comment]
Fixed and released with v3.1.1
