### ISSUE TITLE
Add "Generate without comment" option 

### ISSUE THREAD

**Issue by Muyangmin** [hsz/idea-gitignore#229]
Thanks for this awesome plugin!
Sometimes we want to make *.gitignore* file to be as **simple and clear** as possible, so is this worth to add such an option on generate?
In my opinion, comments for each ignore rule becomes redundant when everyone knows why ignore those files.

**Comment by hsz** [comment]
@mathben Thank you for this suggestion - it's worth implementing. :+1: 

What do you think - how should it be presented to the user ? Another option in the <kbd>Generate</kbd> button expanded list ?

Should it be also somehow combined with `Generate without duplicates` ?

Maybe some additional refactoring options ? If so - how it should work ? I'm open for the new ideas !

**Comment by Muyangmin** [comment]
Hmm……I'm also confused for this question.  I've already think about a checkbox before `Generate` Button so it can be obvious and easily combined with `without duplicates` option. **But if we add more generate option, this combination maybe quickly grows to very duplicated.**  
From my original simple idea, maybe a totally clean ignore file is enough for who want to use this feature. **So maybe another Generate button in expanded list is enough**. (Of course, I don't mind if other users have better ideas!)
