### ISSUE TITLE
Webstorm freeze after update

### ISSUE THREAD

**Issue by matewka** [hsz/idea-gitignore#233]
Hi,
After the recent Webstorm update to version 2016.1.3 I've been experiencing a problem which freezes the IDE. As it turns out, it was caused by the Ignore plugin.

Here's the original issue from Jetbrains youtrack:
https://youtrack.jetbrains.com/issue/WEB-21883

**Comment by lozanro** [comment]
Apparently the isame issue is happening with IntelliJ IDEA 2016.1.3.
Thread dump below.
[threadDump-20160608-122144.txt](https://github.com/hsz/idea-gitignore/files/304499/threadDump-20160608-122144.txt)

**Comment by hsz** [comment]
@matewka @lozanro 
Thanks for the report. Can you please verify it it has been fixed with the attached build ?
[idea-gitignore-233.zip](https://github.com/hsz/idea-gitignore/files/310454/idea-gitignore-233.zip)

**Comment by lozanro** [comment]
Works well with the provided build. Thanks for fixing it.

**Comment by hsz** [comment]
@lozanro thanks for the confirmation. This fix is released in the latest v1.5

**Comment by LeeU1911** [comment]
The old version also freezes on IntelliJ version 15.0.4 and 15.0.6.

I can also confirm it fixed with v1.5.

Thanks a lot!
