### ISSUE TITLE
The plugin crashes when adding special characters to a user template

### ISSUE THREAD

**Issue by alewolf** [hsz/idea-gitignore#234]
When adding the following two lines to a user template the plugin crashes. Note the two invisible \r at the end of the line. I've taken these lines from one of the templates within the plugin. 

```
# Icon must end with two \r
Icon
```

**Comment by hsz** [comment]
@alewolf Can you provide me more information about this error ?

- what version of plugin do you use ?
- what version of IDE do you use ?
- paste the error stack trace

**Comment by hsz** [comment]
@alewolf bump

**Comment by alewolf** [comment]
Sorry. I can't remember exactly how to replicate the issue.
