### ISSUE TITLE
UI to mark favorite inclusions

### ISSUE THREAD

**Issue by bamapookie** [hsz/idea-gitignore#236]
When I add .gitignore files to my project, I almost always add the same few templates: JetBrains, OSX, Node, etc.  It would be nice to have a way of marking these as favorites and bubbling these entries to the top or pre-selecting them.

**Comment by hsz** [comment]
@bamapookie Thank you for this feature request - it may be useful for many users.

I've implemented it and it'll be available in the next release.
Below I've attached some screenshot of the UI implementation:

![image](https://cloud.githubusercontent.com/assets/108333/15988185/db66b662-3046-11e6-88a8-999fe3ed345e.png)

**Comment by bamapookie** [comment]
That's awesome.  Thanks!

**Comment by c33s** [comment]
just for reference, to access this feature do the following:

- navigate to the ignore file
- open it
- right click in the file content area
- choose `Add template...` or `Create user template`

![ignore](https://cloud.githubusercontent.com/assets/649209/17600194/ae74d4a4-6002-11e6-8c2c-ef2bf1d39179.png)

maybe add it to the readme or to a doc directory...
