### ISSUE TITLE
Setting "Enable ignoring" does not really work

### ISSUE THREAD

**Issue by arty-name** [hsz/idea-gitignore#238]
I have a .dockerignore file which ignores all files except for one build artifact. I have unchecked "Enable ignoring" for Docker in Settings - Version Control - Ignore Files Support - Languages settings. Right after I do that everything is good. However soon Idea starts displaying names of all project files in gray, as if they are ignored. Checking and unchecking the checkbox fixes the issue, but soon it appears again.

**Comment by dikderoy** [comment]
I can confirm this. I've encountered same issue in same conditions.

example to reproduce:

assuming a directory `build` exists, `.dockerignore` file contents:
```
!build
*
```

**Comment by hsz** [comment]
@arty-name @dikderoy  
Thank you for reporting this issue.

I cannot reproduce this issue - I've created new `.dockerignore` file with content posted by @dikderoy - it marked all project tree with grey color - then I've unchecked dockerignore "enable" checkbox - gray color disappeared - after that project tree didn't changed back to gray.

Can you provide me more information about it ? What IDE version / plugin version do you use ?
Is there any scenario to get it reproducable (project/modules structure, used VCS)?

**Comment by dikderoy** [comment]
on the moment of appearance I was using:
PHPStorm 2016.1.2

now, I can reproduce on PHPStorm 2016.2

maybe the existance of several ignore files may trigger the bug
on my project I am also have `.gitignore` in project directory. with "enable ignore" enabled for Git.

also - try open several projects at once in multiple windows

contents of `.gitignore` are:

```
/.idea
/node_modules
/src/protected/vendor
/build
/.vagrant
```


![_011](https://cloud.githubusercontent.com/assets/3345611/17066018/b29c1066-504d-11e6-9761-114004112ffa.png)
