### ISSUE TITLE
Plugin .ignore was not installed: Invalid filename returned by a server

### ISSUE THREAD

**Issue by hoangtranwork** [hsz/idea-gitignore#239]
Hi, I'm using IDEA 2016.1.3 on ElementaryOS Freya (Ubuntu 14) and can not install this plugin. Here's the screenshot: https://www.dropbox.com/s/3mpb2olloj93svl/Screenshot_2016-07-10_13.25.16.png?dl=0

**Comment by hsz** [comment]
@hoangtranwork  Thank you for reporting this issue.

That's very strange and it's for sure not related to the plugin itself - it looks like some JetBrains server side issue.
Can you please try again and check if the problem is still reproducable ?

**Comment by nsalin** [comment]
I reproduced this issue, on the latest IDEA version on Windows 10.

**Comment by hoangtranwork** [comment]
@hsz it seems ok with my current environment now. Sorry for the late response.

**Comment by steaks** [comment]
I'm seeing this on 

```
MAC El Capitan 10.11.6. 
IntelliJ Community edition version 2017.2.6. Build IC-172.4574.11. 
JRE: 1.8.0_152. 
JVM: OpenJDK
```
