### ISSUE TITLE
Ignored files in project explorer only colored after editing .gitignore file

### ISSUE THREAD

**Issue by kiview** [hsz/idea-gitignore#246]
I'm running Ubuntu 16.04 and IntelliJ 2016.2 and the .ignore plugin version 1.5.

When I open an existing project, ignored files are only colored grey inside the project explorer once I edit the _.gitignore_ file. 

Before editing:
![screenshot from 2016-07-28 10-31-29](https://cloud.githubusercontent.com/assets/5088104/17206109/80f48362-54ae-11e6-90b3-1322918acf37.png)

After inserting a whitspace:
![screenshot from 2016-07-28 10-32-29](https://cloud.githubusercontent.com/assets/5088104/17206131/9e3bec58-54ae-11e6-81cf-341a1aa70416.png)

**Comment by c33s** [comment]
looks like you mean the VCS coloring. if you use VCS (like git) in phpstorm, the files are 
- `light-gray` if they are `unmodified`
- `blue` if they are `modified`
- `red` if they are `new`
- `green` if they are freshly `added` 
- `gray` if they are `ignored`

you can change the color here (Editor > Colors & Fonts > VCS):
![vcs-color](https://cloud.githubusercontent.com/assets/649209/17628565/2db3ed78-60b6-11e6-81b9-f4d09ff8216f.png)

**Comment by kiview** [comment]
Yes I know, the problem seems to be, that these coloring is only correctly updated/rendered, after I've edited the `.gitignore` file. I'm not sure if this is a bug of the plugin or an IDEA bug?

**Comment by hsz** [comment]
@kiview @c33s 

Thanks for reporting. I've fixed it and it will be available in the next release - v1.6.
