### ISSUE TITLE
Erroneous report of duplicate filenames in PhpStorm 2016.2

### ISSUE THREAD

**Issue by hlev** [hsz/idea-gitignore#247]
The IDE reports and Exception thrown by version 1.5 of the .ignore plugin for duplicate filenames.

Source files are on case-sensitive file system so they are not a duplication. Project metadata (`.idea` folder) is on case-insensitive file system.

**Error message in PhpStorm**
PersistentFS returned duplicate file names(sanity.php,Sanity.php) ignoreCase: true SystemInfo.isFileSystemCaseSensitive: false SystemInfo.OS: Mac OS X 10.11.6 wasChildrenLoaded: false in the dir: file:///<removed path>; children: [Sanity.php (8408), sanity.php (8421), <removed for brewity>] 

PhpStorm 2016.2
Build #PS-162.1121.38, built on July 12, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by hsz** [comment]
@hlev Thank you for this report.

However it's not caused by `.ignore` plugin - it's addressed to the IDE itself. I have already described this problem with: https://github.com/hsz/idea-gitignore/issues/172#issuecomment-166861625
