### ISSUE TITLE
Not working in PHP storm 

### ISSUE THREAD

**Issue by jameschetwood** [hsz/idea-gitignore#249]
This plugin has stopped working for me in PHP Storm. Ive tried both PHP Storm 10.0.4 (it used to work until recently) and Ive just downloaded 2016 with the same result.

**Comment by hsz** [comment]
@jameschetwood Can you describe what is the problem ? Do you have any logs ?

**Comment by lauripiisang** [comment]
Generate gitignore notification doesn't show and action is missing.

**Comment by lauripiisang** [comment]
Apparently workaround to make the plugin realize that we're dealing with a Git project is to create a .gitkeep file and open it!

**Comment by farmisen** [comment]
@lauripiisang workaround apply also to appcode. Thanks!
