### ISSUE TITLE
Coloring ignored files feature request

### ISSUE THREAD

**Issue by otsuka** [hsz/idea-gitignore#251]
I use .gitignore and .dockerignore file in the same project.
The file names defined in both files are colored gray on the project window view,
however, I would like the only files in .gitignore to be colored because I cannot determine that a gray file is ignored by git or docker.

So I would appreciate it if we are able to enable/disable the coloring feature for each .XXXXignore file.

**Comment by hsz** [comment]
@otsuka This feature is already implemented.

Please go to the <kbd>Settings</kbd> > <kbd>Version Control</kbd> > <kbd>Ignore Files Support</kbd> and uncheck the specific file type (*Docker* in your case) in *Enable ignoring* column.

**Comment by otsuka** [comment]
@hsz 

Thank you for your support! 👍
