### ISSUE TITLE
The subfolder won't effected by .gitignore config file.

### ISSUE THREAD

**Issue by Kevin-Misfit** [hsz/idea-gitignore#255]
I've writen a .gitigore file and installed your plugin, it was very clear for use that those files or folders are turned into grey color, but i saw that subfolder won't effected, for example, i want to ignore all build folder, so i wrote a "build/" to .gitignore file, and i saw the first top build folder is turned into grey, but except the subfolder of my Client model, see the screenshot below, could you improve this?

![image](https://cloud.githubusercontent.com/assets/12027816/18428701/10dbb4e2-7902-11e6-8bd9-61fbd9c3603c.png)

**Comment by hsz** [comment]
@Kevin-Misfit Thank you for reporting. It has been fixed right now with #296 and will be delivered soon with v1.7 release.
