### ISSUE TITLE
Default icon

### ISSUE THREAD

**Issue by jzj1993** [hsz/idea-gitignore#258]
I have created a ignore file with a extension ".ignore" defined by myself and edit it with idea-gitignore. It works fine except the files don't have an icon which makes me feel not so good. 

Maybe this plugin can provide a default icon for files which are not in the support file list ? Thanks a lot.

<img width="183" alt="2016-09-23 11 24 19" src="https://cloud.githubusercontent.com/assets/2093721/18773414/a6c2086c-8181-11e6-957b-43af4a99d4f8.png">

**Comment by hsz** [comment]
@jzj1993 Thank you for the report. I've updated it and `.ignore` files will be connectes to the default plugin's icon.
