### ISSUE TITLE
How to disable hints?

### ISSUE THREAD

**Issue by MichalMichalak** [hsz/idea-gitignore#261]
How do I disable hints displayed on top of the editor window? Ex: "Missing .gitignore file in GIT project"

Is there a way to do it? They are obstructing the view and I need to disable them manually by clicking "Cancel" which if not efficient.

**Comment by hsz** [comment]
You can find the option to disable it in the settings:

![image](https://cloud.githubusercontent.com/assets/108333/20543373/1b9704f4-b106-11e6-9f61-eabaf7535404.png)

**Comment by MichalMichalak** [comment]
Thanks.
