### ISSUE TITLE
Setting to provide our own template collection

### ISSUE THREAD

**Issue by TheCodeDestroyer** [hsz/idea-gitignore#271]
Hey it would be really awesome if you could expose the setting where you pull ignore collections from,
so that we can use our forks from [here](https://github.com/github/gitignore)

I would really appreciate if this could be done.

**Comment by hsz** [comment]
@TheCodeDestroyer Thanks for this report !

For now it is possible to specify _User templates_ in the plugin's settings:

![image](https://cloud.githubusercontent.com/assets/108333/19799546/a2cd83da-9cf7-11e6-8d5a-fb93bf5d7fe4.png)

It is possible to import/export user's list to/from file.

As I understand, you anyway would like to fetch another list of `.gitignore` files from very different repository, right ?

For now templates from github/gitignore repository are fetched during the build time - it is not done on the client side. Extending this process with another repository might be complicated (I would like not to provide any _4th party_ templates).
What do you think ?

**Comment by TheCodeDestroyer** [comment]
Are those user templates stored globally or just project based?

**Comment by hsz** [comment]
They are stored globally.

**Comment by TheCodeDestroyer** [comment]
Then that satisfies my needs. Also it would be awesome if we could import files via URL and maybe you store that URL and we can refresh those manually with some refresh button or whatever. Do note that is not needed, but it would be an awesome feature. :)

**Comment by hsz** [comment]
All right, I'll consider some solution related to the sharing user templates in the future. If I'll come with any new solution, I'll let you know.

For now I'm making this issue as invalid because of some changelog generator tool.

**Comment by TheCodeDestroyer** [comment]
Ok thank you very much
