### ISSUE TITLE
Remove user template

### ISSUE THREAD

**Issue by VaclavPavek** [hsz/idea-gitignore#272]
How do I remove custom template?

**Comment by hsz** [comment]
@VaclavPavek Just go to *Ignore Files Support* settings, select specific user template on the list and press <kbd>-</kbd> icon:

![image](https://cloud.githubusercontent.com/assets/108333/19887999/3b851cfa-a02c-11e6-831c-995308f56d9f.png)

**Comment by VaclavPavek** [comment]
Thanks, have a nice day.
