### ISSUE TITLE
The folder "node_modules" In the project, the plug-in makes WebStorm stuck and pop up out of Memory

### ISSUE THREAD

**Issue by chang0022** [hsz/idea-gitignore#273]
# Description
1、I already excluded the "node_modules" folder, ` file->setting->directories`
2、WebStorm stuck  and pop up a window **out of Memory**, and I  can only use ` Ctrl + Alt + Del`
3、I uninstall `.ignore`, and everything is ok

# Version information
Plugin: .ignore v1.5
WebStorm 2016.3 Build #WS-163.7743.25, built on November 10, 2016
JRE: 1.8.0_112-release-408-b2 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
OS: Windows 10
CPU: Intel Core i3-4170 CPU @ 3.70GHz
RAM: 8.00 GB

**Comment by hsz** [comment]
@chang0022 Thank you for reporting !

I've done the fix that will ignore any of the excluded/ignored content in the project (in example - it will not make references between ignore entries to the files in the excluded `node_modules`).

**Comment by chang0022** [comment]
Thanks for fixing it.

**Comment by chang0022** [comment]
@hsz Thanks for fixing it.
