### ISSUE TITLE
Any plan to support Stylint(.stylintignore)?

### ISSUE THREAD

**Issue by JounQin** [hsz/idea-gitignore#279]
`stylint` is not `stylelint`, `postcss` doesn't support `stylus` so linting `.styl` files is not covered by `stylelint`.

`.stylintignore` https://github.com/SimenB/stylint#stylintignore

**Comment by hsz** [comment]
@JounQin Ok, I have fixed this mistake. It'll be delivered in next days with v1.7

**Comment by JounQin** [comment]
Sorry, `stylelint` and `stylint` are different, but both of them should be supported, right?
