### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Joshua-Hager** [hsz/idea-gitignore#280]
Opening a .gitignore file while using this plugin (version 1.6) with OS X 10.11.1 and PhpStorm 2016.3 results with high CPU usage. Please let me know what other info you need to help in debugging.

**Comment by hsz** [comment]
@Joshua-Hager Can you please verify if it happens with the current v1.7.3 version? If so, we'll investigate this problem more deeply.

**Comment by k3n** [comment]
I'm seeing this on OSX 10.10.5 and WebStorm 2016.3.2. Unfortunately, it requires me to edit the file in another editor.

**Comment by Joshua-Hager** [comment]
I am still seeing this behaviour with OS X 10.11.1 and PHPStorm 2016.3.1 using v1.7.5.
