### ISSUE TITLE
.ignore plugin on IntelliJ 13 tries to start multiple copies of the daemon

### ISSUE THREAD

**Issue by eepstein** [hsz/idea-gitignore#282]
Just upgraded to the latest version and got a "fatal" error - so disabled the plugin :-(   
Don't have the stack trace, et. al., but if you're unable to reproduce I'll reenable the plugin and try to do so.

**Comment by hsz** [comment]
@eepstein Can you please verify if it happens with the current v1.7.3 version? If so, we'll investigate this problem more deeply.
