### ISSUE TITLE
feature request: enable editing of templates in-situ

### ISSUE THREAD

**Issue by eepstein** [hsz/idea-gitignore#283]
May have missed this if it's already a feature, but I can't see where to edit the templates used to generate the .gitignore.

Thx.

**Comment by hsz** [comment]
@eepstein Thank you for this feature request.

It is possible to create/modify your own _user templates_ in the plugin's settings:

![image](https://cloud.githubusercontent.com/assets/108333/22861784/be791bca-f121-11e6-8e9e-e1b79c9b7b36.png)

However it's not possible to modify existing ones - the ones provided by the GitHub - I fetch them during the build and deliver built-in to the audience.
