### ISSUE TITLE
Files that are added to repo shouldn't be highlighted as ignored

### ISSUE THREAD

**Issue by WiseBird** [hsz/idea-gitignore#284]
What steps will reproduce the problem?
1. Add filter to .gitignore (eg **/*.js)
2. Manually add file to repo (git add test.js)

What is the expected result?
Filename will not be colored grey

What happens instead?
Filename is highlighted as ignored

**Comment by hsz** [comment]
Thanks for reporting. I've fixed it with #295 and it will be available in the next release.
