### ISSUE TITLE
Ignore Files Support pane scrollbar issue

### ISSUE THREAD

**Issue by mdreizin** [hsz/idea-gitignore#286]
`Ignore Files Support` pane does not have scrollbar for `Language settings` section.

<img width="1552" alt="screen shot 2016-12-23 at 3 16 37 pm" src="https://cloud.githubusercontent.com/assets/279122/21453718/15a83394-c923-11e6-8eac-cdc07cc00b14.png">

WebStorm 2016.3
macOS Sierra 10.12.2

**Comment by mdreizin** [comment]
@hsz Just checked 1.7 (2017-02-11) and now it works fine. Thanks.

**Comment by hsz** [comment]
@mdreizin Thank you for the confirmation!
