### ISSUE TITLE
Git Submodule info/exclude File Support

### ISSUE THREAD

**Issue by tkn98** [hsz/idea-gitignore#287]
This might be either a feature request (if git submodules are not yet supported) or is a report of a flaw (as support for git submodules is incomplete).

The idea-gitignore extension finds my global ignore file properly and does display it as "Outer ignore rules:"

Same is true for the `info/exclude` file within a project (typically the path is `.git/info/exclude`).

However if the project is a git submodule (e.g. the `.git` is not a directory but a file containing the (relative) path to the *modules* folder (e.g. `../../.git/modules`) sub-folder of that submodule (e.g. `../../.git/modules/foo/bar`) then the `ext/exclude` file is *not* displayed as "Outer ignore rules:".

Exemplary in this scenario, the file is:

`../../.git/modules/foo/bar/info/exclude`

If support for these files within the modules info exclude folder would be added, that would be great!

My git version is 1.9.1.

**Comment by hsz** [comment]
@tkn98 Good news - this feature has been finally implemented and will be released with v2.0.0
