### ISSUE TITLE
Files ignored but still tracked

### ISSUE THREAD

**Issue by julienfalque** [hsz/idea-gitignore#295]
With Git, when a file is tracked and then added to `.gitignore` (or whatever ignore list), the file remains tracked until it is completely removed, making the ignore entry ineffective by then. If one edits the file, `git status` will still report the file as modified and allow to commit the changes.

The problem is that the .ignore plugin shows such file as ignored in the IDE despite it's not. Would it be possible to not show the file as ignored as long as it is tracked by Git? Or create a new file status in the IDE to distinguish it from files that are actually ignored?

**Comment by hsz** [comment]
@julienfalque Thank you for this request. It also led to to create something bigger, anyway - finally I got the point and now we can use _native_ VCS colors for modified files, but in addition, there is an information that this file is ignored (by purpose or not).

There is also some baloon notification about this situation which sugests to _untrack_ those files (it calls `git rm --cached` on the selected entries).

![image](https://cloud.githubusercontent.com/assets/108333/22811573/ee3492ba-ef3f-11e6-821b-bdb3034c7d51.png)

(yeah, a lot of new stuff on one screenshot)

**Comment by julienfalque** [comment]
Awesome 👍

**Comment by julienfalque** [comment]
Thank you @hsz :)
