### ISSUE TITLE
subfolder exceptions no longer work

### ISSUE THREAD

**Issue by DeveloperWil** [hsz/idea-gitignore#301]
In my WordPress site .gitignore prior to v1.7 this worked to ignore all the wp-content folders and then specify some sub folders as exceptions. Using PHPStorm 2016.3.2

```
!wp-content/
wp-content/*
!wp-content/mu-plugins
!wp-content/themes/zeropointdevelopment
```

As of v1.7 all of wp-content is ignored and it doesn't seem to pick up any sub folder exceptions.

**Comment by hsz** [comment]
@DeveloperWil 
Thanks for reporting. I've fixed it and it will be available in the next release this morning
