### ISSUE TITLE
IntelliJ IDEA 2017.1EAP (Build #IC-171.3019.7) shows plugin error after upgrade to v1.7

### ISSUE THREAD

**Issue by dejan2609** [hsz/idea-gitignore#303]
```
IntelliJ IDEA (Community Edition) 2017.1 EAP
Build #IC-171.3019.7, built on February 7, 2017
JRE: 1.8.0_121-b13 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
```

- [threadDump-20170211-092808.txt](https://github.com/hsz/idea-gitignore/files/768291/threadDump-20170211-092808.txt)
- [idea.log.txt](https://github.com/hsz/idea-gitignore/files/768293/idea.log.txt)

> 2017-02-11 09:27:08,814 [   4147]  ERROR - llij.ide.plugins.PluginManager - com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null [Plugin: mobi.hsz.idea.gitignore] 
> com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null [Plugin: mobi.hsz.idea.gitignore]
> 	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:249)
> 	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
> 	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:519)
> 	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
> 	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
> 	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
> 	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:285)
> 	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:245)
> 	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$getDefaultProject$3(ProjectManagerImpl.java:307)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:587)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:215)
> 	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:304)
> 	at com.intellij.ide.fileTemplates.FileTemplateManager.getDefaultInstance(FileTemplateManager.java:67)
> 	at org.jetbrains.plugins.scala.actions.NewPackageObjectAction.<init>(NewPackageObjectAction.scala:18)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:419)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:152)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:485)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:473)
> 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1248)
> 	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:34)
> 	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:74)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:181)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:587)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:166)
> 	at com.intellij.openapi.application.Preloader.lambda$initComponent$1(Preloader.java:72)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: com.intellij.diagnostic.PluginException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null [Plugin: mobi.hsz.idea.gitignore]
> 	... 37 more
> Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null
> 	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java)
> 	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:74)
> 	at com.intellij.util.ObjectUtils.assertNotNull(ObjectUtils.java:35)
> 	at com.intellij.dvcs.repo.VcsRepositoryManager.getInstance(VcsRepositoryManager.java:61)
> 	at mobi.hsz.idea.gitignore.util.CacheMap.<init>(CacheMap.java:142)
> 	at mobi.hsz.idea.gitignore.IgnoreManager.<init>(IgnoreManager.java:282)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
> 	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
> 	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
> 	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
> 	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:478)
> 	... 34 more
> 
>

**Comment by CrazyCoder** [comment]
Looks like a duplicate of #302

**Comment by dejan2609** [comment]
Duplicate of #302 **_IllegalArgumentException on IDEA startup_**

**Comment by dejan2609** [comment]
Closing in favor of #302
