### ISSUE TITLE
How to hide ignored files in the project tree view

### ISSUE THREAD

**Issue by PromiseNev** [hsz/idea-gitignore#308]
How to hide ignored files and directories in the project tree view ???

**Comment by hsz** [comment]
Right-click on the Project Tree View and select `Hide ignored files`

![image](https://cloud.githubusercontent.com/assets/108333/22862624/d2f5ba66-f132-11e6-8602-3e5a81b271e2.png)

**Comment by PromiseNev** [comment]
@hsz  thanks!!!
