### ISSUE TITLE
.ignore plugin update notification appears every time a new project is opened

### ISSUE THREAD

**Issue by kedar-joshi** [hsz/idea-gitignore#311]
## **Issue Details**

I just installed the latest .ignore plugin version 1.7.4 and restarted the IDE. After this every time I open a project, IDE shows plugin update notification popup.

This notification should be displayed only the first time plugin (or new version of the plugin) is installed but it is being displayed even after several restarts.

![Update Notification](https://cloud.githubusercontent.com/assets/13585883/22917794/e81b44e4-f2ac-11e6-887a-b688d559020e.png)

## **Version Information**

**Plugin Version:** v1.7.4
**IntelliJ Version:** v2017.1 EAP (171.3019.7)
and
**IntelliJ Version:** v2016.3.4

**Comment by hsz** [comment]
@kedar-joshi Indeed, you're right. I have released an update just right now, thanks.

With this update - the notification will not be shown to the users who already had `v1.7.4`.

**Comment by kedar-joshi** [comment]
Oh My God. This is amazing stuff. I reported this before going to a meeting and I already have an updated release even before the meeting is over. Really appreciate it.

BTW, I can confirm that the new release fixes the issue in both the versions of IDE I had mentioned. Thanks again.
