### ISSUE TITLE
1.7.5 commit fails after idea-gitignore removes files

### ISSUE THREAD

**Issue by narration-sd** [hsz/idea-gitignore#316]
This version is yet cleaner -- no more showing the update message constlantly, for example.  However, something looks wrong after using it to remove unwanted files

expected: Commit after removal works
seen: Commit fails. Image attached showing error, and a re-begin of commit so you can see it was trying to take out the removed files.

Additional Notes that should help:  I had done restarts of PhpStorm 2016.3.2 etc, to try to recover this situation -- nothing worked. Opening the repository with GitKraken, the files showed as WIP to be deleted. I commited in GitKraken with no trouble, and PhpStorm accepts the results. Thus I think you have left PhpStorm somehow in a bad state to cause the fallure to commit there. I'm adding an 
attachment zip of the IDEA log in case there are good clues.

[idea.zip](https://github.com/hsz/idea-gitignore/files/775325/idea.zip)

Steps to replicate:
- create a new PhpStorm project, plus a Git init
- commit the .idea folder and files it will contain
- create a .gitignore files, and add /.idea to it to ignore
- commit that
- use right-mouse 'handle ignored files' (not showing to get that right now) to cause idea-gitignore to put up its dialog asking th take  out the files -- success, so Okay the removal, also success
- refresh the Version Control pane, to show teh removed files, as in the attached image
- attempt to commit them, as in the attached image
- fail to commit with Event alert, expanded in the attached image.

![idea-ignorre-bang](https://cloud.githubusercontent.com/assets/247945/22949475/441ebd0c-f2b7-11e6-84a2-f93cb2495ac3.png)

**Comment by hsz** [comment]
@narration-sd Thank you for creating this ticket.


Regarding to your e-mail that I got this week:

> I could suggest that it could be an option, always visible before allowing the plugin to act, to simply show the proposed Git commands. Then either these could be copied for manual editing/execution, or agreed allowed to execute. At the least, I think this would build a lot more confidence for using your  plugin in our serious projects, even once it’s stable and accepted.

I've prepaded a solution for this case as below:

![image](https://cloud.githubusercontent.com/assets/108333/23001110/da2c3112-f3e3-11e6-8209-728b8ac8bbaf.png)


What do you think?

**Comment by narration-sd** [comment]
It looks great, Jakub. 

I presume the command lines will track any unchecked items, and thus disappear.

**Comment by hsz** [comment]
Yes, it reacts on the tree selection:

![image](http://g.recordit.co/naqayM1cL9.gif)
