### ISSUE TITLE
Preventing or Notification for editing ignored files

### ISSUE THREAD

**Issue by snize** [hsz/idea-gitignore#319]
First of all Thanks for great plugin.
I have a feature request that 'Preventing or Notification for editing ignored files'.
Usually, Hide ignored files and directories in the project tree view works. But sometimes want to reference ignored files.

**Comment by hsz** [comment]
@snize Sounds great, I'll do it. :+1:

**Comment by hsz** [comment]
@snize ignored files should not be prevented from editing. We're ignoring them to don't track the changes - disabling edit possibility will be pointless.

Anyway I have implemented an editor notification about editing this kind of files:

![image](https://cloud.githubusercontent.com/assets/108333/22998990/aa5c5c6e-f3d9-11e6-8632-3fcca7a2519e.png)

It is also possible to disable this feature in plugin's settings:

![image](https://cloud.githubusercontent.com/assets/108333/22999348/2fe59c5a-f3db-11e6-9c33-32ada40db585.png)

**Comment by snize** [comment]
@hsz Thanks! I'm looking forward to next release.

**Comment by hexus** [comment]
Thanks for this! 👍

**Comment by mtnbikenc** [comment]
I found this issue after commenting on #351.  I find it interesting that this feature was implemented about the same time I started seeing the other problem.  Also, no matter what file I'm editing where I get the above notification, it shows the same `.i*` at the beginning of the notification line.

**Comment by eburi** [comment]
Thanks!
