### ISSUE TITLE
Any way to manually invoke "Ignored files found that are tracked" dialogue?

### ISSUE THREAD

**Issue by k3n** [hsz/idea-gitignore#322]
This is a nifty feature, but I'm not sure how/when it's triggered -- I only saw it when I happened to restart WebStorm. It might be handle to be able to bring it up at-will, so that as I make changes to the project and/or ignore files, I can see how those files are affected.

**Comment by hsz** [comment]
@k3n 

Right-click on the Project Tree View and select `Handle tracked and ignored files`

![image](https://cloud.githubusercontent.com/assets/108333/23034173/302183dc-f47b-11e6-88a7-2d8ef9a10444.png)

**Comment by k3n** [comment]
:ok_hand: Thank you!

**Comment by Zteve** [comment]
I don't apparently have this option in my menu. IntelliJ 2017.2.1; plugin 2.0.4.  I'm still seeing the "tracking ignored files" error, and it refers to my project directory; which definitely does _not_ appear in any gitignore file or setting.  Please explain why I'm not seeing this?
