### ISSUE TITLE
Gray out folder in Project panel

### ISSUE THREAD

**Issue by malikoth** [hsz/idea-gitignore#325]
Most of my ignored files and folders display as gray in the project panel, as they should.  However, I added one entry to my `.git/info/exclude` file, and the folder it indicates is not grayed out like everything else that should be ignored.  The `.git/info/exclude` file shows up in the "Outer ignore rules" pane correctly, but entries from it just are not grayed out.

**Comment by hsz** [comment]
@malikoth  thank you for this report. Right now I'm reimplementing the part of the plugin related to the indexing of the ignore files and obtaining the ignored entries. The performance will be improved and various scenarios should be properly covered. Stay tuned!

**Comment by hsz** [comment]
@malikoth This has been implemended with #287 task in the latest release.
