### ISSUE TITLE
PHPstorm stuck

### ISSUE THREAD

**Issue by dunhamdaxia** [hsz/idea-gitignore#333]
When I use it in PHPstorm, when I go to modify the .gitignore file, the editor will stuck. Only one of me encountered this problem? V1.7.6

**Comment by hsz** [comment]
@dunhamdaxia Thank you for this report. Can you please manually install the `v2.0.0-rc.1` package from https://github.com/hsz/idea-gitignore/releases/tag/v2.0.0-rc.1 (zip file)?

I have migrated to the native indexing mechanism provided by the IntelliJ and the performance should be much better for now.

**Comment by hassanazimi** [comment]
@dunhamdaxia I have the similar issue. The IDE gets really laggy and my fan starts working loudly. Whenever a project loads in PhpStorm it tells me that "Ignored files found that are tracked: .ignore plugin found some files that are tracked with Git which are also listed in .gitignore file.
When I start typing I notice "typing speed" is **very low** and IDE sometimes sticks.

**Comment by hassanazimi** [comment]
I confirm that it's been fixed now. thanks very much

**Comment by hsz** [comment]
@hassanazimi Thanks for the confirmation!
