### ISSUE TITLE
Android Template 

### ISSUE THREAD

**Issue by why168** [hsz/idea-gitignore#334]
# Intellij
*.iml
.idea/workspace.xml
.idea/tasks.xml
.idea/gradle.xml
.idea/dictionaries
.idea/libraries

Please change into
# Intellij
*.iml
.idea

**Comment by hsz** [comment]
@why168 thank you for this ticket.
Sorry, but I'll not change them. All templates come from https://github.com/github/gitignore repository.

You can create your own templates with _User Templates_ in plugin's settings.
