### ISSUE TITLE
Allow to disable "You are editing file which is ignored"

### ISSUE THREAD

**Issue by mfursov** [hsz/idea-gitignore#336]
Feature request:  allow to disable "You are editing file which is ignored" inspection for project.

Reason: I usually use some local (.gitignored) folders in project' that are playground for new files / copy-paste or debugging data sets. Every time I create a file in my local folder I see this warning.

**Comment by hsz** [comment]
@mfursov Thank you for reporting this issue.

However you're able to disable this notification in the plugin's settings:

![image](https://cloud.githubusercontent.com/assets/108333/23394770/2f5c1638-fd8b-11e6-84cd-7f0e298dec86.png)

**Comment by mfursov** [comment]
Thank you. This solves my problem.

**Comment by dragonwize** [comment]
Note: You have to have one of the Idea version control integration plugins installed to get to this setting. If you use command line version control by still get the other features of this plugin, you can simply turn on for example the Git Integration plugin, then change this setting, then turn off the integration.
