### ISSUE TITLE
stop sticky balloons popping up during minor version updates

### ISSUE THREAD

**Issue by activedecay** [hsz/idea-gitignore#337]
https://github.com/hsz/idea-gitignore/blob/c403c684f8339807b3ef3a122c8e2f7190b57aa3/src/mobi/hsz/idea/gitignore/util/Notify.java#L86

This is a polite request to stop sticky balloons popping up during minor version updates. I have several plugins installed, and I this is the only project that uses sticky balloons for this purpose. It's not a pleasant experience. (as noted by @jeserkin, there's a bug also where each time the project opens a sticky balloon shows up. I saw this once, but not again.)

**Comment by jeserkin** [comment]
Yeah. Updated recently and constant popping started. Each time I open project this happens.

**Comment by jeserkin** [comment]
Disabled it for now. Not usable in current state. Each project opening requires me to close large popup.

**Comment by hsz** [comment]
@activedecay @jeserkin Is this issue still valid? This problem has been released with the v1.7.6 as far as I remember.

**Comment by activedecay** [comment]
Thanks, I kinda stopped using ij because I'm between jobs. I should get
back to it soon, though. I'll let you know.

**Comment by jeserkin** [comment]
@hsz recently updated to 2017.2 and persistantly poping balloon notification about .gitignore plugin is still present each time I open project in new window.

**Comment by jeserkin** [comment]
@hsz issue is still present. Will it be fixed or should one disable plugin?

**Comment by hsz** [comment]
@activedecay I can suggest you to disable those notifications manually:

![image](https://user-images.githubusercontent.com/108333/30100405-0d203d4e-92e9-11e7-9ea3-ac2f73fca69c.png)

![image](https://user-images.githubusercontent.com/108333/30100422-2791907e-92e9-11e7-8230-fb5c7ec1a182.png)

**Comment by activedecay** [comment]
Nice! Sounds good I'll try that if it becomes an issue for me. Thank you for the follow up. I'm not using the plug-in currently and I don't know that I need it.
