### ISSUE TITLE
Remove untracked files doesn't properly quote names

### ISSUE THREAD

**Issue by bspeice** [hsz/idea-gitignore#339]
When the plugin prompts removing files from Git because they are untracked (i.e. have been committed then added to .gitignore) the plugin nicely prompts that it can remove them. However, the commands it prompts don't quote the files correctly, so the commands fail silently if there are any spaces in the filenames.

Example commands:

```
git rm --cached --force .ipynb_checkpoints/Client Rejections-checkpoint.ipynb
git rm --cached --force .ipynb_checkpoints/CUSUM wrong...-checkpoint.ipynb
git rm --cached --force .ipynb_checkpoints/Rejection Count-checkpoint.ipynb
```

If you actually run these commands, they fail because of the spaces in filenames.

**Comment by hsz** [comment]
@bspeice Thanks for the report, Fix will be available in the latest release.
