### ISSUE TITLE
Hide ignored files and directories in the project tree view

### ISSUE THREAD

**Issue by NatLuder** [hsz/idea-gitignore#348]
Can this be undone somehow in PHPStorm? I need to see my folders, although they won't be submitted to git...

**Comment by hsz** [comment]
@NatLuder Just right-click on the project name and select `Show ignored files`

![image](https://cloud.githubusercontent.com/assets/108333/24155644/b5818f3e-0e54-11e7-8c84-e702318a6d82.png)

**Comment by NatLuder** [comment]
Thanks a lot! :)
