### ISSUE TITLE
Update in "Android.ignore"

### ISSUE THREAD

**Issue by danysz** [hsz/idea-gitignore#349]
Hi

I update in my fork of "gitignore" the "build/" to "**/build/".

I will be really happy if you can take this version to your next version of the plugin.
An android project with multiple modules is just much more comfortable.

Regards

Daniel

**Comment by hsz** [comment]
@danysz  thank you for this ticket.
Sorry, but I'll not change any of template. All templates come from https://github.com/github/gitignore repository.

As an alternative, you can create your own templates with User Templates in plugin's settings.
