### ISSUE TITLE
Invalid "found ignored files included in git"

### ISSUE THREAD

**Issue by zeg-io** [hsz/idea-gitignore#350]
I have a project with a "temp directory" which I want to include but NOT include any files within it EXCEPT for `.gitinclude` file. (so it preserves the directory)

So my `.gitignore` looks like this:

```
#Ensure the files directory is included, but not the contents
tempFiles
!.gitinclude
```

**/tempFiles**
-> **.gitinclude**
-> _otherTempFile.xml_
-> _otherTempFile.xml_
-> _otherTempFile.xml_

However, the plugin is erroneously thinking that `.gitinclude` is supposed to be ignored rather than specifically `un-ingnored`

**Comment by cviebrock** [comment]
Same here, with this structure:

```
/storage
  /cache
    .gitignore
```

And this .gitignore file:
```
*
!.gitignore
```

**Comment by islemaster** [comment]
The plugin also doesn't take into account that a checked-in .gitignore file doesn't ignore itself:
```
/temp
  .gitignore
```
Where .gitignore is simply:
```
*
```
Git still picks up changes to this file.

**Comment by FrancYescO** [comment]
Confirming, this is happening from the last release

**Comment by hsz** [comment]
@zeg-io @cviebrock @islemaster @FrancYescO 

Thank you for this report. I have fixed both (excluding files with `!` and a case with `*`) issues. They will be delivered with the next v2.0.0 release.
