### ISSUE TITLE
Right click file list menu slowed down

### ISSUE THREAD

**Issue by nixolas1** [hsz/idea-gitignore#353]
When right clicking a element in the file tree menu the right click menu takes 5-10 seconds to open.
The project this happened in is a pretty large node + episerver (csharp) project, which has 40000 files, only 700 of which are not ignored.
Using latest webstorm and had just installed plugin.

**Comment by hsz** [comment]
Related to #335

**Comment by hsz** [comment]
@nixolas1 Can you please confirm if this also happens in the latest `v.2.1.1` ?

**Comment by nixolas1** [comment]
The issue is gone in v 2.1.1 👍
