### ISSUE TITLE
Strange behavior with tracked ignored files detection

### ISSUE THREAD

**Issue by julienfalque** [hsz/idea-gitignore#359]
When I open a specific project, the plugin shows an _"Ignored files found that are tracked"_ notification, but when I click _"Show details"_, the popup only shows the project root directory. It even happens if I clear or remove the .gitignore file.

Edit: I think I know what's causing the issue: in recent PhpStorm releases, one can _include_ several projects inside another main project window. In my case, the tracked ignored files were in one of these included projects, not in the main one. When I opened the project with those files in its own window, I was able to untrack them.

Is it possible that the plugin is able to find the tracked ignored files in all projects of a window, but the popups only shows the one that are in the main project?

**Comment by julienfalque** [comment]
I think I know what's causing the issue: in recent PhpStorm releases, one can _include_ several projects inside another main project window. In my case, the tracked ignored files were in one of these included projects, not in the main one. When I opened the project with those files in its own window, I was able to untrack them.

Is it possible that the plugin is able to find the tracked ignored files in all projects of a window, but the popups only shows the one that are in the main project?

**Comment by hsz** [comment]
Can I ask you to check if this issue is still present in v2.1.1?

**Comment by julienfalque** [comment]
I won't be able to reproduce the specific "several projects in the same windows" case but I also faced the issue with other "simple" projects (like reported in other issues) and this seems to be fixed by v2.1.1 so I think you can close this issue, thanks!
