### ISSUE TITLE
Why are some project files randomly showing up as ignored after installing .gitignore plugin for PhpStorm

### ISSUE THREAD

**Issue by Sameh-R-Labib** [hsz/idea-gitignore#364]
I added the .gitignore plugin to PhpStorm a few weeks ago and out of the blue one of my project files turns grey in the project bar.

This happens randomly like one or two files a day on average. They weren't being ignored before but now they are although I haven't changed anything in the .gitignore file or any other Git configuration file.

Has this happened to anyone else? Has anyone figured out what's going on?

**Comment by mko-x** [comment]
Probably same as #361

**Comment by hsz** [comment]
@Sameh-R-Labib Thanks for the report, I'll mark it as a duplicate of #361. I'm on it!
