### ISSUE TITLE
Invalid entry in Gradle template (/build/)

### ISSUE THREAD

**Issue by bamapookie** [hsz/idea-gitignore#371]
The Gradle template ignores '/build/', but that does not cover build directories in modules.  Could it be replaced with 'build/' ?

**Comment by hsz** [comment]
Thank you for this report.

All of the available template come from the 3rd party repository provided by GitHub and are bundled with the plugin. It is not possible to modify them here with this plugin, however you can create your own templates with rules that you want.

**Comment by bamapookie** [comment]
I'll take it upstream, then.  Thanks!
