### ISSUE TITLE
Unused entry markin all lines in Dockerfile

### ISSUE THREAD

**Issue by seiyapl** [hsz/idea-gitignore#374]
Please see this link for details: https://youtrack.jetbrains.com/issue/IDEA-174706

**Comment by hsz** [comment]
@seiyapl Thank you for this report.

```
ADD target/cargo.war $JETTY_BASE/webapps/ROOT.war
```

This is not a valid content so it will not be correctly handled by the plugin.

I guess that you have put `Dockerfile` entries into `.dockerignore` file.

**Comment by seiyapl** [comment]
Hi,
This is not .dockerignore file and I do not have such file in my project at all. This is the file that is used to build the docker image and it seems to be OK with the rules (see https://docs.docker.com/engine/reference/builder/#add).

**Comment by hsz** [comment]
Issue caused by misleading names. This case will be handled with #375
