### ISSUE TITLE
File type for .dockerignore should not be named 'Docker'

### ISSUE THREAD

**Issue by borlander** [hsz/idea-gitignore#375]
Extracted from https://youtrack.jetbrains.com/issue/IDEA-174706

Actually the filetype for .dockerignore files is named Docker in UI. 
See attached screenshot showing 2 competing same-named Docker entries. 

<img width="720" alt="screen shot 2017-06-20 at 13 51 45" src="https://user-images.githubusercontent.com/1390992/27332311-aecedb4c-55c1-11e7-9ae4-9ea041b407dd.png">

The black icon is from ignore plugin while "with-D" icon is from the Docker support plugin. 
The fact that the black-whale icon is actually much nicer :) probably only contributes to the confusion of the users. 

In addition to UI name, the key used to store the filetype association is actually also "Docker file" which is again competing with the official Docker support plugin, see the following extract from <config-root>/options/filetype.xml file: 

```
<application>
  <component name="FileTypeManager" version="17">
    <extensionMap>
      <mapping ext="custom-dockerignore" type="Docker file" />
      <mapping pattern="custom-docker-file" type="Dockerfile" />
```

The latter (the key in the options file) is more difficult to change, but UI name should be easy to fix. 
Thanks

**Comment by hsz** [comment]
@borlander Thanks for this ticket. I agree with you that people can be confused with the very simmilar name.

I'll refactor those names (not only Docker but all the other file types too) and publish it with v2.0.0

**Comment by hsz** [comment]
@borlander Ok, I've updated the displayed name of the ignore-file types. Currently it looks like:

![image](https://user-images.githubusercontent.com/108333/27789603-7891b244-5fed-11e7-9541-c75e8f4f4e31.png)
