### ISSUE TITLE
Suggestion: Reformat Header/Section/Line Comments

### ISSUE THREAD

**Issue by TigerC10** [hsz/idea-gitignore#378]
It's kinda hard to read through the ignore file created by this plugin, sometimes.  I would suggest flipping the comment headings to be more in line with markdown syntax.  That is, changing the format of the templates to invert the single/triple headings like so:
```
# Header element

## First section
*.jar
*.war
*.ear
out/

## Second section
.gradle/
build/

### .gitignore negations
!out/foo.txt
!bar/

### Mercurial syntax switch
syntax: glob
```

Not that you'd ever necessarily put this into a markdown parser, but reading markdown is pretty common for devs and the way the template generator works now goes in the opposite direction that markdown does.

**Comment by hsz** [comment]
@TigerC10 Thansk for that.

To be honest, it'll be a hard to achieve, because https://github.com/github/gitignore templates contain one `#` character in their entries:

https://github.com/github/gitignore/blob/d5ce0fc1d4a677eaa60d5b8e01ac9e42ec7cfcd1/C.gitignore#L1-L13
