### ISSUE TITLE
Handling of multi module project with parent and children in separate git repos

### ISSUE THREAD

**Issue by leonroy** [hsz/idea-gitignore#383]
I have a multi module IntelliJ project which looks like:

```
my-app
├── pom.xml
├── .gitignore
├── auth-server
│   └── src/main/java
│   └── pom.xml
│   └── .gitignore
├── api-server
│   └── src/main/java
│   └── pom.xml
│   └── .gitignore
└── web-client
    └── src/main/js
    └── src/main/css
    └── pom.xml
    └── .gitignore
```

Parent is a Java project with a couple of child modules.

The parent *.gitignore* obviously ignores the child modules already in their own git repos so I'm not committing them twice:

ie.

    api-server/
    auth-server/
    web-client/

The *.ignore* plugin throws up *You are editing file which is ignored* for any child module source code even though the child git repo is different to the parent's and hence should not inherit the parent *.gitignore* rules.

* How should the plugin be handling this scenario?
* Is there any sort of work around?

**Comment by bradacjan** [comment]
I have a simillar issue, where the modules are symlinked to a parent project for convenience . 
And after updating PhpStorm and the .gitignore plugin, I get the extremely annoying popup "You are editing file which is ignored".

It would be great if it was possible to disable the popup in settings (for people who run into scenarios like this). 

The entire filename and tab name are grayed out, that is more than enough to notice that I am editing an ignored filename. And PhpStorm already alerts you if you are editing files outside of project scope. So the popup seems redundant to me.

I really like your plugin and would love to keep using it. It is very helpful and has been nicely unobtrusive so far. I would have loved it to stay that way.

**Comment by hsz** [comment]
@bradacjan You can disable this _You are editing file which is ignored_ message in the plugin's settings:

![image](https://user-images.githubusercontent.com/108333/28756906-30d26fd4-7578-11e7-8edf-83f9b39ae839.png)

**Comment by bradacjan** [comment]
Great, that works. I could not find that before, thank you.
