### ISSUE TITLE
Java Stream Debugger plugin works fine for standalone application, but failed in existing project

### ISSUE THREAD

**Issue by bhagatdinesh** [hsz/idea-gitignore#392]
Standalone application means:
public static void main(String[] args) {
        int[] res = Arrays.stream(new int[]{10,32,65,1,1,1,3,5,2,3,4,5,6})
                .distinct()
                .sorted()
                .toArray();
    }
This works fine.
<img width="1289" alt="screen shot 2017-07-27 at 12 31 43 pm" src="https://user-images.githubusercontent.com/3823705/28658197-bac75fe6-72c7-11e7-98d6-b6193b175979.png">

Now If I add following code to any existing method which is Resource method for RestUrl.
 int[] res = Arrays.stream(new int[]{10,32,65,1,1,1,3,5,2,3,4,5,6})
                .distinct()
                .sorted()
                .toArray();
Then it throws an exception which is not relevant to above line of code. Also, there is no compilation problem or run time problem.
As I understand correctly, I added a break point at the start of above code and Trace current stream chain button will be activated, click that button or Alt+o command, will bring stream trace window. 
<img width="1398" alt="screen shot 2017-07-27 at 12 35 19 pm" src="https://user-images.githubusercontent.com/3823705/28658542-754bf312-72c9-11e7-86ef-2937eaeeb75f.png">

Let me know what wrong I am doing.

**Comment by hsz** [comment]
@bhagatdinesh I'm not a developer of _Java Stream Debugger _

This is .ignore plugin's repository GH page.
