### ISSUE TITLE
Hi CPU usage whilst coding with version 2.0.0

### ISSUE THREAD

**Issue by courtney-miles** [hsz/idea-gitignore#396]
After upgrading .ignore plugin to version 2.0.0 I have found PHPStorm to be very sluggish.

As I type, the CPU spikes and there's a delay typing every character and a delay with autocomplete options being populated.

Disabling the .ignore plugin solves the issue.

These are my PHPStorm About details.

```
PhpStorm 2017.2
Build #PS-172.3317.83, built on July 18, 2017
JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.8.0-58-generic
```

Let me know if there's more information I can provide.

**Comment by vcraescu** [comment]
Same on MacOS. I just uninstall because it makes intellij unusable.

**Comment by radutopala** [comment]
@hsz same on 2.0.3, both PHPStorm and Gogland

**Comment by b1rdex** [comment]
Same for me, phpstorm is very laggy. Cpu hogs even if I don't type, it happens on some constant interval.

**Comment by hsz** [comment]
@vcraescu @radutopala @b1rdex  and this happens during the working with IDE (not for example indexing), right?

**Comment by b1rdex** [comment]
@hsz yes, there is problem after indexing finished.

**Comment by vcraescu** [comment]
@hsz yes, even after indexing finished. Not even touching the IDE and the CPU stays at ~120%.

**Comment by AndrewSologor** [comment]
Same problem on linux after last update. IDE became unusable. Uninstalled.

**Comment by hsz** [comment]
@courtney-miles @vcraescu @radutopala @b1rdex @alpham8 @BramDriesen

Can you please check if following build's stability is better?
[idea-gitignore-2.0.3.zip](https://github.com/hsz/idea-gitignore/files/1187811/idea-gitignore-2.0.3.zip)

**Comment by b1rdex** [comment]
@hsz looks like problem fixed

**Comment by cdimauro** [comment]
I had the same issue using PyCharm: https://youtrack.jetbrains.com/issue/PY-25432

Tested the last build now works! :)
