### ISSUE TITLE
Ignored files found that are tracked

### ISSUE THREAD

**Issue by bogdanpuica** [hsz/idea-gitignore#400]
Ignored files found that are tracked: .ignore plugin found some files that are tracked with Git which are also listed in .gitignore file.

**Comment by alexantr** [comment]
After last update in every project which I reopen .ignore plugin shows this message and suggests to untrack project root folder.

**Comment by MichalMichalak** [comment]
I am receiving the same message and the suggestion is to remove files that, indeed are ignored, but are not committed nor staged to be committed. I am using GIT.

Again to be clear - plugin shows me the files that are only on my disk, locally, never went to remote repository and will not go there because they are ignored, ex: `.idea` directory.

**Comment by alexilyaev** [comment]
That doesn't make sense, it says there are files that are `tracked` and `ignored`, meaning they somehow got added to the repo before ignoring them.

I think it's a bug, I have a repo which has no tracked files that are satisfied by `.gitignore` patterns:  
https://github.com/alexilyaev/react-es6-starter

The plugin in WebStorm doesn't show me anything when I click `Show Details`.

**Comment by alexantr** [comment]
What I see in every project:

![1](https://user-images.githubusercontent.com/4941848/28876816-1955e58e-77a3-11e7-9ba1-5f20f6fcd04c.png)
![2](https://user-images.githubusercontent.com/4941848/28876818-1b9c0508-77a3-11e7-8fbb-9a4f8b62f4c8.png)

.gitignore file:

```
.idea/
vendor/
build/
composer.lock
composer.phar
phpunit.xml
phpunit.phar
```

**Comment by ali-shamakhi** [comment]
I got a list of some tracked but ignored files, tried to fix them by running the suggested commands:
`git rm --cached --force file_path_to_be_reset`
but I got this for every command:
`fatal: pathspec 'file_path_to_be_reset' did not match any files`
and I checked them, they really didn't exist!

After that, I get this at every IDE start:
![empty-list-of-tracked-ignored-files](https://user-images.githubusercontent.com/10486368/28886366-7c6904c8-77ce-11e7-9ba0-2c9af2878de8.PNG)

**Comment by kamronbatman** [comment]
+1, same problem as everyone else.  Using Webstorm 2017.2.1.

**Comment by r3b311i0n** [comment]
I have the same issue on Idea 2017.2.1

**Comment by joshmorel** [comment]
This started happening as soon as I upgraded the plugin to 2.0.4  (WebStorm 2017.2.1 & 2017.2.2)

Before the plugin upgrade it was working

**Comment by svenbergryen** [comment]
same here. PhpStorm PhpStorm 2017.2.1 (Build #PS-172.3544.41, built on August 2, 2017) and idea-gitignore-2.0.4


![untrack_ignored_files_and_eu-cookie-compliance-port-css-changes-2900108-4_patch_-_eu8_-___webserver_eu8__and_eu_cookie_compliance_module_-_eu-cookie-compliance_-___webserver_eu_cookie_7_sites_all_modules_eu-cookie-compliance_](https://user-images.githubusercontent.com/904345/29002529-fc361352-7aa4-11e7-88fb-c1124b126f7a.jpg)

**Comment by mbuzdalov** [comment]
I also have this issue, manifesting itself in every project just like above. IDEA 2017.2.1, .ignore 2.0.4.

**Comment by CAD97** [comment]
👍 Occurring for me in IDEA 2017.2.1 as well. No repro in 2017.2.2 because #443 supersedes any plugin action.

**Comment by richardhooper** [comment]
+1 for this issue!
PhpStorm 2017.2.1 (Build #PS-172.3544.41, built on August 2, 2017)
.ignore 1.7.6 (I've been letting this update when suggested, but maybe I should be doing a manual upgrade...)

I've got a number of projects I'm actively developing, but only one of them seems to suffer from this issue.
