### ISSUE TITLE
"Outer" ignore rules include extraneous files

### ISSUE THREAD

**Issue by CAD97** [hsz/idea-gitignore#401]
(Windows)

My project is at `D:\CAD97\Documents\Code\Rust\project`. This plugin is displaying 55 "Outer ignore rules" from `~/.cargo/registry/src/.../.gitignore` where `~` is `C:\Users\CAD97\` and `C:\Users\CAD97\.cargo` is a symlink to `D:\CAD97\.cargo`.

As neither `D:\CAD97\.cargo` nor `C:\Users\CAD97\.cargo` nor `~/.cargo` are a parent of `D:\CAD97\Documents\Code\Rust\project`, I am not exactly certain why these files got picked up by the plugin as outer `.gitignore` files.

This started happening upon updating the plugin (to v2.0.4). I was on 1.7.6 previously (the previous version in the JetBrains Plugin Repository).

**Comment by CAD97** [comment]
Installing [Rust + Cargo](https://rustup.rs/) and using Cargo to set up a project with dependencies should set up this situation.

**Comment by hsz** [comment]
@CAD97  thank you for this report.
I'll try to setup this environment and reproduce your case.
