### ISSUE TITLE
Plugin slows down machine 

### ISSUE THREAD

**Issue by tzfrs** [hsz/idea-gitignore#407]
Hello,

I'm using this plugin for several years now and am pretty satisfied. However, since PhpStorm 2017.2 I have massive performance problems. My machine stops for a second every five seconds where I can't do anything. Scrolling is lagging, no autocompletion etc. When I open the "Open file" dialog it takes seconds till it opens.

First I thought it's because of the Symfony Plugin, but I disabled the plugins one by one and only after disabling this plugin, PhpStorm ran smoothly again. As I said, this problem only exists since the last few updates of PhpStorm, never had problems with it.

Is there a way you can confirm this @hsz ? Because I'd hate to leave it disabled, but it's currently the only way to guarantee a good performance.

I invalidated caches already ofc.

**Comment by hsz** [comment]
@tzfrs what version of plugin do you have installed?

**Comment by tzfrs** [comment]
Oh, sorry @hsz, didn't realize you answered that fast

I currently have .ignore plugin version: `2.0.3`.

**Comment by hsz** [comment]
@tzfrs can you please update to 2.0.4?

**Comment by tzfrs** [comment]
When I try to update I'm getting the notice `You already have the latest version of plugins installed`

**Comment by hsz** [comment]
https://plugins.jetbrains.com/plugin/download?updateId=37362

**Comment by hsz** [comment]
@tzfrs  ok, or added new release. Please install it manually

**Comment by tzfrs** [comment]
Will do tomorrow and report back.

**Comment by tzfrs** [comment]
@hsz: So far no problems!

**Comment by squatto** [comment]
I can also confirm that 2.0.3 destroys PhpStorm performance. I'm on a Mac, PhpStorm 2017.2, and had to disable this plugin to make my IDE remotely usable. 2.0.3 has the same changelog as 2.0.4 in my IDE though, and I can't update to 2.0.4. For now, I have to keep it disabled.

**Comment by squatto** [comment]
Strangely, I updated PhpStorm to 2017.2.1 and now I only see .ignore version 1.7.6. It doesn't even tell me that 2.x is an option.

<img width="841" alt="screen shot 2017-08-05 at 8 37 42 pm" src="https://user-images.githubusercontent.com/748444/29000077-f5affe9e-7a1d-11e7-8334-874eaf272398.png">

**Comment by narration-sd** [comment]
@squatto , I'm on the latest EAP also, and I don't see this problem. 2.04 is visible and still installed after the update.

This is on Win10, but a Mac shouldn't be different, as it's all Java for JetBrains.

You might try removing the plugin, rebooting, and reinstalling it? Or maybe before that, just a Check for Updates?

**Comment by squatto** [comment]
@narration-sd Even after removing and restarting the app, "Browse Repositories" only shows 1.7.6. I got around it by downloading the 2.0.4 release .zip and manually installing it. Hopefully it catches anything beyond this version though.

**Comment by roman-1983** [comment]
I got the same problem with PHPStorm 2017.2.1 and .ignore 2.0.3.

Looks like update to 2.0.4 solved it for me!

**Comment by hsz** [comment]
@roman-1983 @squatto @tzfrs Thanks for the confirmation!
