### ISSUE TITLE
gitignore files from gems are shown in the outer ignore rules

### ISSUE THREAD

**Issue by bughit** [hsz/idea-gitignore#410]
RM 2017.1.5 idea-gitignore 2.0.4

e.g. ~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/unicorn-4.9.0/Documentation/.gitignore

**Comment by CAD97** [comment]
At the very least related to #401

**Comment by hsz** [comment]
Duplicate of #401
