### ISSUE TITLE
FileStatusManager.getStatus is slow after installing the plugin

### ISSUE THREAD

**Issue by nicity** [hsz/idea-gitignore#415]
IDE calls getStatus very-very often, e.g. for every icon rendered in project view so the method should be really fast.

In CPU snapshot attached to https://youtrack.jetbrains.com/issue/IDEA-176946 (private customer issue) 20s of getStatus calculation is spent in 
mobi.hsz.idea.gitignore.vcs.IgnoreFileStatusProvider.getFileStatus(VirtualFile).

There are several problems with the method according the snapshot:
- There is disk access for IgnoreFilesIndex.getKeys(myProject) (10s) and it is called for every isIgnored calculation. The (short term) suggestion is to cache the same value.
- There is disk access for IgnoreFilesIndex.getEntries(Project, IgnoreFileType) (4s), I suspect that some entries are not relevant to the project and proper set of ignore files for project can be calculated once and cached as well
- There is 2s in java.util.regex.Matcher.matches(), there is O(N) number of .gitignore patterns (probably some char trie can help)
- Also there is 1.5s in getOuterFiles(Project)

**Comment by hsz** [comment]
@nicity How can I access those memory snapshots? Can you please provide me URLs?

**Comment by nicity** [comment]
Merged callees

+-------------------------------------------------------------------------------------------------------------------------------------------+-----------------+-----------------+
|                                                             Merged Call Tree                                                              |    Time (ms)    |  Own Time (ms)  |
+-------------------------------------------------------------------------------------------------------------------------------------------+-----------------+-----------------+
|  +---mobi.hsz.idea.gitignore.IgnoreManager.isFileIgnored(VirtualFile) IgnoreManager.java                                                  |  20,717  100 %  |            190  |
|    |                                                                                                                                      |                 |                 |
|    +---mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.getKeys(Project) IgnoreFilesIndex.java                                           |  10,913   53 %  |              0  |
|    |                                                                                                                                      |                 |                 |
|    +---mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.getEntries(Project, IgnoreFileType) IgnoreFilesIndex.java                        |   4,057   20 %  |              0  |
|    |                                                                                                                                      |                 |                 |
|    +---java.util.regex.Matcher.matches() Matcher.java                                                                                     |   2,267   11 %  |          2,267  |
|    |                                                                                                                                      |                 |                 |
|    +---mobi.hsz.idea.gitignore.lang.IgnoreLanguage.getOuterFiles(Project) IgnoreLanguage.java                                             |   1,771    9 %  |              0  |
|    |                                                                                                                                      |                 |                 |
|    +---com.intellij.dvcs.repo.VcsRepositoryManager.getRepositoryForFile(VirtualFile) VcsRepositoryManager.java                            |     671    3 %  |              0  |
|    |                                                                                                                                      |                 |                 |
|    +---com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getPath() VirtualFileSystemEntry.java                                  |     205    1 %  |              0  |
|    |                                                                                                                                      |                 |                 |
|    +---mobi.hsz.idea.gitignore.file.type.kind.GitExcludeFileType.getWorkingDirectory(Project, VirtualFile) GitExcludeFileType.java        |     203    1 %  |              0  |
|    |                                                                                                                                      |                 |                 |
|    +---com.intellij.openapi.project.impl.ProjectImpl.getBaseDir() ProjectImpl.java                                                        |     138    1 %  |              0  |
|    |                                                                                                                                      |                 |                 |
|    +---mobi.hsz.idea.gitignore.indexing.ExternalIndexableSetContributo

**Comment by hsz** [comment]
@nicity Thanks for the call tree. I played with YourKit regarding the methods call counts, time, etc and fixed a few more things too.

From my point of view everything should be fine now - it's released with v2.1.0-RC.1 (available in eap channel (https://plugins.jetbrains.com/plugins/eap/7495) or https://github.com/hsz/idea-gitignore/releases/tag/v2.1.0-RC.1

Can you please confirm that?

Is there anything else that should be fixed before new public release?

**Comment by nicity** [comment]
Great! 
Lets do the release and check for users's feedback.
I'll post newer issues with profiler information if needed.
