### ISSUE TITLE
The following plugins are incompatible with the current IDE build: .ignore

### ISSUE THREAD

**Issue by sivviswa22** [hsz/idea-gitignore#416]
I am using the following intellij version
IntelliJ IDEA 2017.2.2
Build #IC-172.3757.29, built on August 8, 2017
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

I have tried after installing the latest v2.0.4 (2017-07-31)

**Comment by sivviswa22** [comment]
I have tried with the latest v2.0.4 (2017-07-31) installed manually as well.

**Comment by BorzdeG** [comment]
duplicate: #408

**Comment by GuillaumeHemmen** [comment]
This problem happened again, please re-open this issue or let me know if I need to post a new issue.

IDE details :
PhpStorm 2018.1.1
Build #PS-181.4445.72, built on April 9, 2018
JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**Comment by andy-radkevich** [comment]
I installed the plug-in from the idea-gitignore-2.6.0-RC.1.zip. The problem is solved. Many thanks.

**Comment by joaoferrao** [comment]
Where exactly did you find the 2.6.0 version? I can only find the 2.5.0 to download manually

**Comment by vikbert** [comment]
updating the plugin `.ignore` fixed my problem .
