### ISSUE TITLE
Plugin not found in repositories

### ISSUE THREAD

**Issue by donalmurtagh** [hsz/idea-gitignore#428]
In the latest release of IntelliJ 

IntelliJ IDEA 2017.2.2
Build #IU-172.3757.52, built on August 15, 2017

I tried searching for this plugin using both "ignore" and ".ignore", but it isn't shown in either case.

**Comment by hsz** [comment]
@donalmurtagh  thanks. This is related to the #408

**Comment by donalmurtagh** [comment]
Thanks for your quick response, it seems I just need to wait for you to release a version that JetBrains are happy with, is that right?

**Comment by hsz** [comment]
@donalmurtagh that's correct.
