### ISSUE TITLE
Broken v1.7.6 with IntelliJ IDEA v2017.2.2

### ISSUE THREAD

**Issue by darkfishy** [hsz/idea-gitignore#444]
After updating IntelliJ IDEA on 20th of August, 2017 around 14:00 AEST, the plugin was reported as broken. See error message below:

	Plugin Error
	Problems found loading plugins:
	The following plugins are incompatible with the current IDE build: .ignore

IntelliJ IDEA 2017.2.2
Build #IU-172.3757.52, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

Hope this helps.

**Comment by sealte** [comment]
Same problem

**Comment by arkbriar** [comment]
same problem

**Comment by hsz** [comment]
Duplicate of #408
