### ISSUE TITLE
Plugin replaced the action "New Scratch"

### ISSUE THREAD

**Issue by BorzdeG** [hsz/idea-gitignore#448]
version: 2.1.0-RC.1

demo: https://youtu.be/qFIVyox9gHM

![screen 0](https://habrastorage.org/web/9d3/16c/8a0/9d316c8a063247759dab9a02dd2f46b1.png)
![screen 1](https://habrastorage.org/web/bab/d56/bbb/babd56bbb6f34ab99041d3aba58e7975.png)

**Comment by hsz** [comment]
Nothing has been replaced. :)
This modal window contains a list of all available language types in the IDE. Because they all starts with dot, they are on the top of the list. 

You can still search within this list (by typing) or just scroll down:

![demo](http://g.recordit.co/o9Dmsocv3y.gif)

**Comment by BorzdeG** [comment]
Oh, the visual lack of scrolling and a large list of templates knocked me off :(

**Comment by keetron** [comment]
Is there a setting to turn this off?
I liked my scratch list as it was...

**Comment by hsz** [comment]
@keetron Nothing from my side was performed - I guess that JB has changes something in their core.

**Comment by keetron** [comment]
I'll get used to the search function :smile:
Thinking of it, it is only in new projects a minor issue as the most recently used languages are listed up top. Thanks for the reply!

**Comment by hsz** [comment]
@keetron Anyway I agree that a 10+ .#ignore entries on the top of this list can be really annoying. I'll take a look if there is any possibility to hide them in any way before going with the next release. Stay tuned!

**Comment by monk-time** [comment]
> I'll take a look if there is any possibility to hide them in any way before going with the next release. Stay tuned!

@hsz, any news?

**Comment by hsz** [comment]
After a digging in the IntelliJ SDK it appeared that "New Scratch" list is filled with all available languages with some filter applied - i.e. `Language` that implements `InjectableLanguage` interface will be excluded.

Other base functionalities seem to be working correctly, so it was a quick solution.
It'll be released with the next version of the plugin.

**Comment by monk-time** [comment]
@hsz, hooray! Thank you for the blazingly fast response.

**Comment by hsz** [comment]
Fix has been published with `v2.2.2`.
