### ISSUE TITLE
I can't find it in IDEA's plugins

### ISSUE THREAD

**Issue by eden214** [hsz/idea-gitignore#449]
windows10    idea2017.2.2

**Comment by hsz** [comment]
Duplicate of #408

**Comment by eden214** [comment]
@hsz I mean I can't FIND .gitignore follow these steps:Preferences > Plugins > Browse repositories... > Search for ".ignore". Not mean I can't USE it. I can find it some idea version before, but it disappeared on 2017.2.2.

**Comment by hsz** [comment]
@eden214 because of https://github.com/hsz/idea-gitignore/issues/408#issuecomment-321644030 blacklisted version of the plugin don't appear in the listing.

Future v2.1.0 release (which is in progress now) will be visible again.
