### ISSUE TITLE
.ignore fails to load on IDEA 2017.2.2

### ISSUE THREAD

**Issue by jbauerrfid** [hsz/idea-gitignore#452]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

####
No stack trace available, no exception was thrown.

### Description

Output from Event Log tab:
```
Plugin Error
Problems found loading plugins:
The following plugins are incompatible with the current IDE build: .ignore
```

Output from `~/.IntelliJIdea2017.2/system.log`:
```
2017-08-23 11:24:43,429 [   1760]   INFO - llij.ide.plugins.PluginManager - Plugin '.ignore' can't be loaded because: This plugin version was marked as incompatible 
```

### Versions

**Plugin:** 

```
1.7.6
```

**IDE:** 

```
IntelliJ IDEA 2017.2.2
Build #IU-172.3757.52, built on August 15, 2017
Licensed to *************
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-32-generic
```

**OS:** 

```
Ubuntu 16.04 LTS
```

**Comment by hsz** [comment]
Thanks - it will be fixed with v2.1.1 quite soon.

**Comment by jbauerrfid** [comment]
It seems to be fixed with v2.1.0 - but it does not update automatically from 1.7.6 - rather it is required to uninstall 1.7.6, then download 2.1.0 as zip and install the new plugin from disk.

**Comment by izatop** [comment]
@jbauerrfid i did try to uninstall and install downloaded 2.1.0 zip file and it doesn't working for me (Ubuntu 17.04 and WebStorm 2017.2.2.

![screenshot from 2016-12-13 15-04-28](https://user-images.githubusercontent.com/2235586/29610463-e52e687e-8802-11e7-85ac-e104e3dd5264.png)

**Comment by hsz** [comment]
Because of some critical bug I had to pull this update down. However JB Support still didn't remove this update entry from their registry.

I'm about to release v2.1.1 soon with proper fixes, so everything should be fine again.
Stay tuned.

**Comment by jbauerrfid** [comment]
Just click "Install plugin from disk..." and point to the `idea-gitignore-2.1.0.zip` - this worked for me.

**Comment by oranheim** [comment]
Installing from a source code archive doesn't work. Can you release a IDEA Jar Plugin archive?

**Comment by hsz** [comment]
@oranheim https://github.com/hsz/idea-gitignore/releases

**Comment by oranheim** [comment]
@hsz only sources has been release. No compile plugin is avail for release, only for RC1..

**Comment by hsz** [comment]
v2.1.1 has been released

**Comment by oranheim** [comment]
Perfect! It works fine in IDEA 2017.2.2 :) Thank you !!

**Comment by jbauerrfid** [comment]
Updates automatically to v2.1.1 and works perfectly.
