### ISSUE TITLE
Update templates in ignore file when upstream updates.

### ISSUE THREAD

**Issue by bamapookie** [hsz/idea-gitignore#459]
Feature request:

When upstream updates a template, detect the update and update the .gitignore file.  Might require including a commit hash in the file.  If ignore file has been customized, resolve issue with a three way diff.

**Comment by hsz** [comment]
@bamapookie Thanks for this request. It's interesting, indeed - but the effort on both (mine and the end user) is quite too high comparing to the potential benefits.

First of all - currently templates update is provided only with the new version of the plugin (we cannot assume that user has installed git repository - and simply fetch to the machine something provided in 3rd party repo - it can be treated as a security issue).

Also inserting tempalte's hash into the generated file is quite problematic - what if somehing will be changed inside this file or even hash will be removed?
