### ISSUE TITLE
Files/folders marked as ignored in IntelliJ's project are shown as 'never used' in the .gitignore file

### ISSUE THREAD

**Issue by drewnoakes** [hsz/idea-gitignore#47]
Specifically, I have marked the `.idea` folder as ignored in the project panel (or project structure -- it's the same.)

Now the `/.idea` entry in the `.gitignore` file has a yellow squiggly line saying:

> '/.idea' entry is never used

Also, IntelliJ generates classes into the `/out` folder, and this is marked as 'never used' as well.

![image](https://cloud.githubusercontent.com/assets/350947/3898910/e4e832e4-2272-11e4-9a26-8c762fc8c3f8.png)

---

Other files in there (such as `/nbproject`, `*.project` and so on) apply to other developer's project structures which are not in the repo. I don't understand the value of marking these to look like errors. It might be more sensible to display them as redundant (greyed out).

**Comment by VasekPurchart** [comment]
Hi, I just started using PHPStorm and found this great plugin, but immediately stumbled upon this issue, my first guess was that it has something to do with excluded folders, which it obviously does.

I just wonder why is this issue closed? I think it is still reported with false positives and previous comments here tell the same tale?
