### ISSUE TITLE
Feature request: add an option to avoid "You are editing a file which is ignored" message

### ISSUE THREAD

**Issue by IgorJorobus** [hsz/idea-gitignore#481]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet

### Description

Could you please add an option to avoid "You are editing a file which is ignored" message? It is annoying when you have to open a lot of ignored files and that message drops again and again and must be manually closed. Thank you very much in advance, the plug-in is great.

### Versions

**Plugin:** 

2.2.1

**IDE:** 

Rubymine 2017.2.4

**OS:** 

Windows 10 Enterprise x64

**Comment by hsz** [comment]
@IgorJorobus This feature is already available in plugin's settings:

![image](https://user-images.githubusercontent.com/108333/30984580-feecd1ea-a48d-11e7-9788-08639094ffb9.png)

**Comment by IgorJorobus** [comment]
Disregard then. Thanks for the quick response.

**Comment by dragonwize** [comment]
Note: You have to have one of the Idea version control integration plugins installed to get to this setting. If you use command line version control by still get the other features of this plugin, you can simply turn on for example the Git Integration plugin, then change this setting, then turn off the integration.
