### ISSUE TITLE
The .upignore should not tell the IDE to actually ignore files

### ISSUE THREAD

**Issue by mrmark** [hsz/idea-gitignore#483]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [X] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

The `.upignore` should not tell Intellij to actually ignore files.  While the contents behave like a `.gitignore` file, it is not meant to actually ignore files in the editor.  It is used to provide a whitelist or blacklist of files to include in the build zip.  Example contents from the [docs](https://apex.github.io/up/#configuration__ignoring_files):

```
*
!app.js
!package.json
!node_modules/**
!src/**
```
So, this would ignore all docs, README, etc, when building the zip asset, but it shouldn't tell the IDE to ignore those files as well.

### Steps to Reproduce

I was using PHPStorm.

1. Create an `.upignore`
2. While editing the `.upignore`, get benefits from plugin this regarding paths, etc.

**Expected behavior:** _What you expect to happen_

The paths in `.upignore` do not cause the editor to actually ignore files.  Ideally, you can still apply the benefits of this plugin to the editing of the `.upignore` files.  But, if it is all or nothing, I suggest revert supporting this file.

**Actual behavior:** _What actually happens_

The paths in `.upignore` cause the editor to ignore files.  You then get notifications about editing an ignored file.

**Reproduces how often:** _What percentage of the time does it reproduce?_

100%

### Versions

**Plugin:** 

2.2.1

**IDE:** 

PHPStorm 2017.2.4

**OS:** 

macOS Sierra 10.12.6

**Comment by hsz** [comment]
@mrmark Thank you for this report. It's fixed and will be released with v2.2.2

**Comment by mrmark** [comment]
Awesome, thanks so much for you time!

**Comment by hsz** [comment]
Fix has been published with `v2.2.2`.
