### ISSUE TITLE
Plugin makes IDE too slow

### ISSUE THREAD

**Issue by ericmccain** [hsz/idea-gitignore#490]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

A month ago or so my PhpStorm started to work extremely slow. Almost any action like scrolling or pressing buttons was performed after significant delay. I tried to disable as many plugins as possible and finally got that .ignore plugin slows IDE. Enabling slows, disabling it removes the issue.
No any visible error logs. No indexation. It happens in a few minutes (maybe, ten) after restarting IDE.

### Versions

**Plugin:** 

```
The latest at the moment version (2.2.2). The same happened in previous versions.
```

**IDE:** 

```
2017.2.4
```

**OS:** 

```
Ubuntu 16.04
```

**Comment by hsz** [comment]
@ericmccain Thanks for this report!
I have released `v2.3.0-RC.1` on EAP channel. Can you please check if it solves this issue for you?

**Comment by fogush** [comment]
@hsq hello, I've created this issue while logging in by a wrong account, sorry for the mess :)
After two days of using, it seems the issue is fixed, thanks a lot!

**Comment by hsz** [comment]
@fogush That's great, thank you for the confirmation!
