### ISSUE TITLE
Opening .gitignore makes IDE too slow

### ISSUE THREAD

**Issue by fogush** [hsz/idea-gitignore#492]
### Prerequisites

* [x] Plugin is in the latest version
* [X] Issue was not reported yet

### Description

After updating to the last version to fix an issue described in https://github.com/hsz/idea-gitignore/issues/490, the plugin continued to make IDE slow.
It happens just by opening .gitignore. It slows at the same moment or in a few seconds. Any click and any action are performed with a freeze. It continues to happen even .gitignore is closed, just one opening is enough.

### Versions

**Plugin:** 

```
v2.3.0-RC.1
```

**IDE:** 

```
2017.2.4
```

**OS:** 

```
Ubuntu 16.04
```

### Additional Information

Also I noticed IDE analyzes this file during commit too long, about a minute:
![selection_351](https://user-images.githubusercontent.com/2500435/32374814-49e69666-c0b0-11e7-8610-0ef7a8736baa.png)

My file contains about 90 lines of ignored files/folders. Project is quite big.
Do you need some additional info?

**Comment by hsz** [comment]
@fogush can you please upgrade plugin to V2.3.0¿?

**Comment by fogush** [comment]
@hsz ah, sorry, I was so stupid to believe the version is still the same as a few days ago and even didn't check updates :(
I don't see freezes with the new version, it seems it work. Thanks for the quickest answer and your work!
