### ISSUE TITLE
Missing/Wrong Key IGNORE.UNUSED_ENTRY in colour scheme

### ISSUE THREAD

**Issue by NikolayMetchev** [hsz/idea-gitignore#494]
the plugin seems to be contributing the wrong  entry in the color scheme settings (see attached image).
I incorrectly filed it as an idea bug here (https://youtrack.jetbrains.com/issue/IDEA-181624)

![unused entry](https://user-images.githubusercontent.com/417373/32553112-d5f289b8-c48d-11e7-840e-e25bca907f1d.PNG)

**Comment by hsz** [comment]
@NikolayMetchev Thank you for this report. It's fixed and will be released in v2.3.1

**Comment by hsz** [comment]
Fix is released and available with v2.3.2

**Comment by NikolayMetchev** [comment]
Thanks @hsz I can confirm it's fixed. I did notice however that in the .ignored section of the colour selection there is not unused item example.

![no ignored file example](https://user-images.githubusercontent.com/417373/33123481-4124243c-cf72-11e7-9ad4-f3ba58144402.PNG)
