### ISSUE TITLE
Gitignore may be breaking Jetbrains index caches

### ISSUE THREAD

**Issue by y3sh** [hsz/idea-gitignore#495]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet

### Description

The devs on YouTrack believe this is an issue with .gitignore: https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000626684-Almost-every-day-PHPStorm-forgets-all-classes-und-functions-until-invalidate-cache-?page=1#community_comment_115000596790

### Steps to Reproduce

1. Install plugin in webstorm or phpstorm
2. Complete file index
3. Quit IDE, Reboot, IDE index cache is broken

**Expected behavior:** 

Does not break IDE index cache.

**Actual behavior:** 

Break IDE index cache.

**Reproduces how often:** _What percentage of the time does it reproduce?_

Every time

### Versions

 2.3.0

Webstorm 2017.2
Phpstorm 2017.2
Mac OS

**Comment by hsz** [comment]
@y3sh Thanks for this report. It looks like an effect of the issue reported in #493 

It was fixed in [v2.3.2](https://github.com/hsz/idea-gitignore/releases/tag/v2.3.2)

Can you please install this build and check if it solves this problem?

**Comment by hsz** [comment]
New version has been released to the plugins repository and approved by JetBrains team.

**Comment by CrazyCoder** [comment]
@hsz could you please check https://youtrack.jetbrains.com/v2/issue/IDEA-181404#comment=27-2553523 ?
