### ISSUE TITLE
Dead EAP link

### ISSUE THREAD

**Issue by SUPERCILEX** [hsz/idea-gitignore#500]
There's a link on the main README to download the EAP version of this plugin, but IntelliJ keeps saying I have the wrong link. Hopefully just a simple fix! 😄

**Comment by SUPERCILEX** [comment]
@hsz Any updates?

**Comment by SUPERCILEX** [comment]
@hsz Any updates?

**Comment by hsz** [comment]
@SUPERCILEX Because of the problematic updates mechanism (long waiting time for update acceptance from JB), this EAP channel makes no sense.
