### ISSUE TITLE
irritating donation pop-up

### ISSUE THREAD

**Issue by JunkMail4MJD** [hsz/idea-gitignore#506]
This is an idea for adding an un-install button to the irritating balloon that pops up asking for PayPal donations.

For Intellij Idea users that are sick of this pandering for money on a plugin that frankly does extremely little. It can save them a few button clicks to un-install this plugin (like I just did).

Hopefully others will enjoy this new feature as well.

**Comment by hsz** [comment]
@JunkMail4MJD There is no need to do that.
IDE allows to turn off permanently any notifications from the specific plugin/group:

![image](https://user-images.githubusercontent.com/108333/33942530-8a5d3954-e016-11e7-9525-f1b97b87c704.png)
![image](https://user-images.githubusercontent.com/108333/33942564-a57e0a42-e016-11e7-9bff-cde2e9df5281.png)

**Comment by toolforger** [comment]
Actually I find the request more irritating than .ignore's behaviour; obviously, that person does not know how much work a plugin is, or how much it actually does.
Don't let freeriders like this one irritate you, Jakub.

I see the opportunity for a small UX improvement here: Rename the entry from "IGNORE_GROUP_UPDAT<whatever>" to something human-readable, like ".ignore donation reminder".

**Comment by hsz** [comment]
v2.4.0 has been released.
