### ISSUE TITLE
Not able to ignore file from Version Control->Unversioned Files view

### ISSUE THREAD

**Issue by serg-bloim** [hsz/idea-gitignore#509]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Use case: I have one or several unversioned files in the project. In order to find and ignore them, I go to Version Control->Local changes->Unversioned Files

There is an option to ignore them using IDEA's built-in ignore. But if I want to ignore them using the plugin, I have to switch to project view for every file.

**Comment by hsz** [comment]
@serg-bloim Thank you for creating this ticket. I have implemented such possibility - it will be released with v2.4.0 today.

![image](https://user-images.githubusercontent.com/108333/34821030-a4fdb92e-f6c2-11e7-9867-c20db4bb9311.png)

**Comment by hsz** [comment]
v2.4.0 has been released.
