### ISSUE TITLE
Problems found loading plugins: The following plugins are incompatible with the current IDE build: .ignore

### ISSUE THREAD

**Issue by liaozan** [hsz/idea-gitignore#512]
### Prerequisites

* [x] Plugin is in the latest version 2.3.2
* [x] Issue was not reported yet 
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description
idea'version 2017.3.3 early access program

when i update the idea to lasted version:
Problems found loading plugins: The following plugins are incompatible with the current IDE build: .ignore
my English sucks..sorry

_Description of the issue_

```
Stack trace if available.
```

### Steps to Reproduce

1. _First Step_
2. _Second Step_
3. _and so on..._

**Expected behavior:** _What you expect to happen_

**Actual behavior:** _What actually happens_

**Reproduces how often:** _What percentage of the time does it reproduce?_

### Versions

**Plugin:** 

```
Can be found in Settings > Plugins > .ignore
```

**IDE:** 

```
Can be found in Help > About. Click on the copy icon on the left.
```

**OS:** 

```
Information about operation system - type, version.
```

### Additional Information

_Any additional information, configuration or data that might be necessary to reproduce the issue._

**Comment by hsz** [comment]
Depends on releasing #510 
New version of the plugin (v2.4.0) will be released today.

**Comment by hsz** [comment]
v2.4.0 has been released.
