### ISSUE TITLE
[Feature] Make .git/info/exclude window read / write

### ISSUE THREAD

**Issue by valorize** [hsz/idea-gitignore#514]
It would be great if the .git/info/excude window would be read/write. So I can add own custom, not versioned excluded files to it

**Comment by hsz** [comment]
@valorize Thanks for creating this issue.

Bottom list is and will be read-only. However you can click on the file's path to open specific _exclude_ file and edit it there.

**Comment by valorize** [comment]
Thank you very much thats a valuable tip :)
