### ISSUE TITLE
the show members function of class file not working

### ISSUE THREAD

**Issue by MIMIEYES** [hsz/idea-gitignore#516]
When I installed the igore plugin, the class show members function of the IDE failed. Unfortunately, I can't use it for the time being.

**Comment by hsz** [comment]
@jimschubert  please create issue filling all required information using the template.
Without stacktrace, information about plugin or IDE version I can't help you.

**Comment by MIMIEYES** [comment]
Sorry. I'm going to recreate one.

**Comment by hsz** [comment]
Thanks!
