### ISSUE TITLE
.ignore file is too aggressive - excludes codeStyle settings

### ISSUE THREAD

**Issue by madmongo1** [hsz/idea-gitignore#519]
### Prerequisites

* [X ] Plugin is in the latest version
* [ X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

_Description of the issue_

When auto-generating .gitignore for Jetbrains, the following line is emitted:

```
.idea/*
```
This is too aggressive. The following path should be stored in git:

```
.idea/codeStyles/*
```

### Steps to Reproduce

1. Create a .ignore file
2. select "Jetbrains"
3. click "generate"

**Expected behavior:** _What you expect to happen_

selected directories and files in the .idea/ folder to be ignored

**Actual behavior:** _What actually happens_

.idea/* is emitted in addition

**Reproduces how often:** _What percentage of the time does it reproduce?_

100%

### Versions

2.4.0

```
Can be found in Settings > Plugins > .ignore
```

**IDE:** 
CLion

```
Can be found in Help > About. Click on the copy icon on the left.
```

**OS:** 
```
Linux driveby.local 4.14.18-300.fc27.x86_64 #1 SMP Thu Feb 8 01:35:31 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hsz** [comment]
@madmongo1 
All of the templates - incl. JetBrains one - come from the https://github.com/github/gitignore repository.
However the one that you mention: https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore doesn't even contain `.idea/*` rule.

**Comment by madmongo1** [comment]
Hum. I'll create a new project and check again. Suggest you assume it's my error, and I'll re-investigate.
