### ISSUE TITLE
Support .ebignore files

### ISSUE THREAD

**Issue by basicdays** [hsz/idea-gitignore#520]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

AWS Elastic Beanstalk has their own ignore file called `.ebignore`. It works like the standard `.gitignore` file. You can find a bit more information here: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-configuration.html#eb-cli3-ebignore

### Steps to Reproduce

N/A

### Versions

**Plugin:** v2.4.0
**IDE:** IntelliJ Ultimate 2017.3.4
**OS:** Kubuntu 17.10

### Additional Information

N/A

**Comment by hsz** [comment]
@basicdays Thanks for the request. It'll be released with `v2.5.0`

**Comment by basicdays** [comment]
Amazing, thanks!
