### ISSUE TITLE
Untracked Ignored Files Shows Directory Outside Git Repo

### ISSUE THREAD

**Issue by nlacombe-creditshop** [hsz/idea-gitignore#528]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
I only found issue #523 which seems similar but in that issue the file showing in the popup is also listed in a gitignore file and is inside a repo.
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

"Untracked Ignored Files" popup shows up and list a directory which is outside all of my git repos.
More specifically it shows my intellij project directory which is not a child and not a parent of my git repos.

### Steps to Reproduce

1. Open up Intellij (possibly with directory structure similar to mine)

**Expected behavior:** no "Untracked Ignored Files" popup or at least my no files/directories listed under "Untracked Ignored Files" popup which are not part of a git repo.

**Actual behavior:** I see the "Untracked Ignored Files" popup listing my intellij project folder which is not in a git repo.

**Reproduces how often:** 100% of the times I tried to reproduce it (a few times but I remember seeing the popup very often before as well).

### Versions

**Plugin:** 
2.5.0

**IDE:** 
IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
Licensed to Nicolas Lacombe
Subscription is active until January 4, 2019
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**OS:** 
macOS 10.13.4
Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64

### Additional Information

Popup screenshot:
<img width="1094" alt="screen shot 2018-04-04 at 10 54 46" src="https://user-images.githubusercontent.com/30241844/38317213-80a0fe0a-37fa-11e8-88af-bfc90848d956.png">

Console output that shows that the "work-all" directory is not inside a repo.
<img width="496" alt="screen shot 2018-04-04 at 11 15 26" src="https://user-images.githubusercontent.com/30241844/38317228-89f9d6b6-37fa-11e8-87e8-75399c0193e1.png">

Console output that shows the directory structure: where the work-all directory is compared to the git repo.
<img width="178" alt="screen shot 2018-04-04 at 10 51 44" src="https://user-images.githubusercontent.com/30241844/38317258-9dd386f0-37fa-11e8-96c3-a657393acdeb.png">

**Comment by CombeeMike** [comment]
Seems related to https://youtrack.jetbrains.com/issue/IDEA-189590 with the difference, that my project folder actually is inside a git repo but shouldn't be reported as an ignored file.

**Comment by hsz** [comment]
This feature will be disabled with v3.1.0
