### ISSUE TITLE
Do not hide ignored files in Project View

### ISSUE THREAD

**Issue by mike-neck** [hsz/idea-gitignore#529]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

The feature to hide ignored files in Project view introduced in 2.5.0 is inconvinient. For example after running `./gradlew test`, I want to see the report file(it's under `build` directory) from IntelliJ IDEA, but it is not available from Project View.

### Steps to Reproduce

1. Add any pattern to ignore file.
2. Create any file or any directory matching the pattern.

**Expected behavior:** 

* The ignored file or the files under the ignored directory can be viewed in Project View. 

**Actual behavior:** 

* The ignored files is not available from Project View.

### Versions

**Plugin:** 

```
2.5.0
```

**IDE:** 

```
IntelliJ IDEA 2018.1
```

**OS:** 

```
Mac OSX(High Sierra)
```

**Comment by hsz** [comment]
@mike-neck 

This is how this feature should work - under the right mouse putton we have <kbd>Show/Hide ignored files</kbd> entry.
If you want to have those files visible, just click it again:

![image](https://user-images.githubusercontent.com/108333/38560386-ccfb568a-3cd5-11e8-9bcf-05535f14b924.png)

By default all ignored files are visible and grayed out.

**Comment by mike-neck** [comment]
Thanks! If you didn't give me this advise, I would disable the plugin.

**Comment by hsz** [comment]
@mike-neck I should reconcider the UX in this case. :)
