### ISSUE TITLE
The following plugins are incompatible with the current IDE build

### ISSUE THREAD

**Issue by yabasha** [hsz/idea-gitignore#530]
### Prerequisites

* [X] Plugin is in the latest version
* [ ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description
Plugin Error
 Problems found loading plugins:
 The following plugins are incompatible with the current IDE build: .ignore

installing the latest version of PHPStorm 2018.1.1

### Steps to Reproduce

1. Update PHPStorm to latest version (2018.1.1)

**Actual behavior:** 
IDE error message that the plugin is not compatible with IDE version

**Reproduces how often:**
100%

### Versions

**Plugin:** 

```
2.5.0
```

**IDE:** 

```
2018.1.1
```

**Comment by arcticlinux** [comment]
```
Plugin Error
			Problems found loading plugins:
			The following plugins are incompatible with the current IDE build: .ignore
```

Traceback
```
2018-04-09 14:25:45,249 [   3031]   INFO - llij.ide.plugins.PluginManager - Plugin '.ignore' can't be loaded because: This plugin version was marked as incompatible 
```

**Comment by leehom1988** [comment]
yes, i have the same peoblem, waiting for fix it.

**Comment by nicity** [comment]
https://github.com/hsz/idea-gitignore/issues/527#issuecomment-379742978
https://youtrack.jetbrains.com/issue/IDEA-189189

**Comment by weinde** [comment]
same problem

**Comment by 912d** [comment]
I have the same issue, although not in the PhpStorm but in **IntelliJ IDEA 2018.1.1 (Community Edition)**
_Build #IC-181.4445.78, built on April 9, 2018
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0_

![obraz](https://user-images.githubusercontent.com/7474972/38572994-0945a16c-3cf5-11e8-8017-a9ffd2033908.png)

**Comment by robert-cody** [comment]
>  Maxim Mossienko  10 Apr 2018 11:34
> We disabled existing versions of .ignore plugin in IDE updates.
> https://github.com/hsz/idea-gitignore/issues/527#issuecomment-379742978

**Comment by szagot** [comment]
Same problem...

> **Plugin Error**
> Problems found loading plugins:
> The following plugins are incompatible with the current IDE build: .ignore

**Comment by MichaelGatesDev** [comment]
Same issue here on IntelliJ Ultimate latest stable build and plugin version 2.5.0.

**Comment by iltar** [comment]
```
PhpStorm 2018.1.1
Build #PS-181.4445.72, built on April 9, 2018
Subscription is active until March 26, 2019
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-62-generic
```

**Comment by chinaerserver** [comment]
The same for me

IntelliJ IDEA 2018.1.1 (Ultimate Edition)
Build #IU-181.4445.78, built on April 10, 2018
JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**Comment by Scott-G** [comment]
+1 for me too

PhpStorm 2018.1.1
Build #PS-181.4445.72, built on April 9, 2018
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by narration-sd** [comment]
come on guys -- this is getting pretty boring, all these same/plus1s.

It doesn't help anything, and if you pay attention, you'll find this is for a reason being worked,  as with all the other times for this plugin.

**Comment by iltar** [comment]
It's broken and not the first or second time after an update. A lot of people rely on certain behaviour of this plugin and it's an annoyance if it randomly stops working. I'd fix it myself, but I don't know how.

I think it's a must have feature for jetbrains to include in their platform, maybe that would help stability the of this plugin?

**Comment by hsz** [comment]
@iltar 

As already mentioned above (https://github.com/hsz/idea-gitignore/issues/527#issuecomment-379742978), JB has disabled v2.5.0 because it has conflicts with new release of their IDEs.
FIx is ready (#527 issue, #531 PR), I'm waiting for the confirmation/code review/whatever from @nicity to avoid releasing fix and getting reverted again.
After releasing it'll take another couple days for accepting the update by some approval team.
I can't do more about that, sorry.

**Comment by iltar** [comment]
> I can't do more about that, sorry.

@hsz, you don't have to be sorry, you're not being paid to do this, are you? :+1: 

 I don't think anyone is explicitly at fault here, but it's a shame that it keeps breaking. This plugin is really useful for my development workflow in PhpStorm and I instantly notice it when it does not work.

**Comment by hsz** [comment]
@iltar I'm not paid for that, just the occasional donations via PayPal. ;-)
It's great to hear that you consider this plugin useful!


Ok, `v2.6.0` has been finished and released to the JB repository. Now we have to wait for their move.
Until then, it's available for manual installation in [Releases tab](https://github.com/hsz/idea-gitignore/releases/tag/v2.6.0)

**Big thanks to @nicity for the support! 👏 **

**Comment by mathiasbader** [comment]
same for me :-/

**Comment by LeeLear** [comment]
same for me
