### ISSUE TITLE
.ignore causes PyCharm to freeze

### ISSUE THREAD

**Issue by cLupus** [hsz/idea-gitignore#536]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Whenever I open the projects `.gitignore` file, PyCharm (2018.1.1) (macOS 10.13.4) freezes, and the fan goest to overdrive.
The freezing stops when I close `.gitignore`.

```
Stack trace if available.
```

### Steps to Reproduce

1. _First Step_
2. _Second Step_
3. _and so on..._

**Expected behavior:** The file to open, and can be edited normally

**Actual behavior:** PyCharm freezes

**Reproduces how often:** Always (after newest version)

### Versions

**Plugin:** 

```
2.6.1
```

**IDE:** 

```
2018.1
```

**OS:** 

```
macOS 10.13.4
```

### Additional Information

When deactivating the plugin, `.gitignore` can be opened normally, without freezing PyCharm

**Comment by hsz** [comment]
Can you please provide thread dump?

**Comment by cLupus** [comment]
I was unable to do so.
Turns out, "Turning it off, and on again" worked. I.e. I reinstalled the plugin (after deactivating it).
