### ISSUE TITLE
Line markers are generated on composite elements

### ISSUE THREAD

**Issue by zolotov** [hsz/idea-gitignore#538]
See https://youtrack.jetbrains.com/issue/GO-5599

According to the user disabling `.ignore` plugin fixes performance issue and removes all `LineMarker is supposed to be registered for leaf elements only` messages from log.

**Comment by hsz** [comment]
This issue was already fixed with https://github.com/hsz/idea-gitignore/commit/7e8017010eece6395a10e5fc83abb1949c22a6a0#diff-72b0e71ccec75dbec6615bd092129d0aR94
and released in `v2.6.1`.
