### ISSUE TITLE
.gitignore entries using wildcard never considered as used

### ISSUE THREAD

**Issue by julienfalque** [hsz/idea-gitignore#543]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

In a .gitignore file, entries like e.g. `foo/*/baz.txt` are never considered used despite they do match a file (the file appears as ignored in the Project view and `git status` does not report it as untracked).

The issue does not occur if the wildcard is used along with some explicit characters, e.g. `foo/ba*/baz.txt`.

### Steps to Reproduce

1. Create the following file in your project: `aaa/bbb/ccc.txt`
2. Add the following entry to .gitignore file: `aaa/*/ccc.txt`
3. Notice that the file is correctly ignored: everything works as expected but the entry is considered unused
4. Change the entry to `aaa/b*/ccc.txt`
5. Now everything works as expected *and* the entry is considered used

**Expected behavior:** I expect the entry to be considered used at step 3 and 5.

**Actual behavior:** The entry is considered used at step 5 only.

**Reproduces how often:** always.

### Versions

**Plugin:** 2.6.1
**IDE:** 2018.1.2
**OS:** Ubuntu 16.04

**Comment by hsz** [comment]
@julienfalque Thanks for this report. It's fixed and released with v2.6.2

**Comment by julienfalque** [comment]
Thank you @hsz :)

**Comment by julienfalque** [comment]
I confirm the issue is fixed, thanks again!
