### ISSUE TITLE
Implement a .deployignore file to override / add to the excluded paths

### ISSUE THREAD

**Issue by metaa** [hsz/idea-gitignore#544]
So I made a tool to automatically deploy files for my company last weekend and I created a `.deployignore` file to define what's excluded from that deployment.

But since that idea of an `.deployignore` file has been a thing to me for a while now, I just wanted to ask if it were possible to include functionality to this plugin to read such a file and use it to add to the excluded paths feature of the deployment section of the JetBrains IDEs?

Another way would be to have an option to **import** those excludes from that file (just like you'd open the npm tasks panel)

![image](https://user-images.githubusercontent.com/5056880/40023562-c24a5c34-57cb-11e8-8a4b-27e4956f14fc.png)

I think it would make teamwork much easier in some places as only the person to create the file would have to set up what's excluded and others then wouldn't have to set it all up again 😊

**Comment by metaa** [comment]
Another way would be to have an option to **import** those excludes from that file (just like you'd open the npm tasks panel)

![image](https://user-images.githubusercontent.com/5056880/40023562-c24a5c34-57cb-11e8-8a4b-27e4956f14fc.png)

**Comment by metaa** [comment]
Any input on this? 🤔

**Comment by hsz** [comment]
@metaa I have reviewed the overall idea of this feature request. To make it possible, I'll have to inject the proper values into the IDE configuration.
_Deployment_ section in IDE settings is not available in the community version, so it's not possible to review the code and put those values with IDEA SDK.

![image](https://user-images.githubusercontent.com/108333/46030330-20d33300-c0f6-11e8-93de-2f3e8ebd1034.png)

**Comment by metaa** [comment]
Oh yeah, I didn't think of that 🤔

**Comment by hsz** [comment]
@metaa Just did additional research - settings values related to this specific option is not stored externally in IDE configuration files, so it's not even possible to bypass the SDK and set it via file system.
No can do, sorry.

**Comment by metaa** [comment]
For what I know there's keepass files that store deployment info but ...ehh ... yeah, you'd have to ask the user for the password and stuff, so maybe not.
