### ISSUE TITLE
Ignored files found that are tracked (ignoring folder except a single file)

### ISSUE THREAD

**Issue by Smartsasse** [hsz/idea-gitignore#547]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Getting the message "Ignored files found that are tracked - .ignore plugin found some files that are tracked with Git which are also listed in .gitignore file".
The file it finds is "/application/uploads/16.pdf" and my .gitignore looks like this
`
/application/uploads
!/application/uploads/16.pdf
`

So you can clearly se that the whole uploads-folder should be ignored except that one file so I shouldn't get this message.

```
Stack trace if available.
```

### Steps to Reproduce

1. Ignore one folder in .gitignore
2. Exclude ignore for one single file in that folder in .gitignore
3. Restart PHPStorm. Maybe need to have checked in the .gitignore file, not sure.

**Expected behavior:** I expect .ignore-plugin not to complain about this

**Actual behavior:** .ignore-plugin complains about this

**Reproduces how often:** 100% (showing after restarting PHPStorm)

### Versions

**Plugin:** 2.6.2

```
Can be found in Settings > Plugins > .ignore
```

**IDE:** 2018-1

```
Can be found in Help > About. Click on the copy icon on the left.
```

**OS:** Mac OS High Sierra 10.13.4

```
Information about operation system - type, version.
```

**Comment by hsz** [comment]
This feature will be disabled with v3.1.0
