### ISSUE TITLE
user tpl can't update/save when current has opened project

### ISSUE THREAD

**Issue by bluelovers** [hsz/idea-gitignore#548]
### Prerequisites

* [ x] Plugin is in the latest version
* [ ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

user tpl can't update when current has opened project

the only way is close all project and then edit setting

**Expected behavior:** _What you expect to happen_

i can update use tpl when i current has opened project

**Actual behavior:** _What actually happens_

need close all project, then edit setting for make change is realy save

**Reproduces how often:** _What percentage of the time does it reproduce?_

### Versions

**Plugin:** 

```
Can be found in Settings > Plugins > .ignore
```

**IDE:** 

```
Can be found in Help > About. Click on the copy icon on the left.
```

**OS:** 

```
Information about operation system - type, version.
```

### Additional Information

_Any additional information, configuration or data that might be necessary to reproduce the issue._

**Comment by hsz** [comment]
Changes done during creating/editing user templates are applied instantly even when the project is opened.
It is possible to generate new `.gitignore`-like file using those templates.

Cannot reproduce.
Please check if you are using the latest IDE with lates plugin version.
