### ISSUE TITLE
npmignore dir

### ISSUE THREAD

**Issue by bluelovers** [hsz/idea-gitignore#550]
### Prerequisites

* [x] Plugin is in the latest version
* [ ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

when we add folder by menu

it add
```
/screenshots/
```
this will not ignore /screenshots/ when npm publish

only

```
/screenshots
```

or

```
screenshots
```

**Expected behavior:** _What you expect to happen_

should not publish screenshots folder

**Actual behavior:** _What actually happens_

screenshots folder got publish

**Reproduces how often:** _What percentage of the time does it reproduce?_

### Versions

**Plugin:** 

```
Can be found in Settings > Plugins > .ignore
```

**IDE:** 

```
Can be found in Help > About. Click on the copy icon on the left.
```

**OS:** 

```
Information about operation system - type, version.
```

### Additional Information

_Any additional information, configuration or data that might be necessary to reproduce the issue._

**Comment by hsz** [comment]
When adding `/screenshots/` to the `.npmignore`,, `screenshots` directory located in the root of the project will not be published.
I couldn't reproduce your issue:

```
$ npm pack      
npm notice 
npm notice 📦  middy-secrets@0.2.1
npm notice === Tarball Contents === 
npm notice 867B   package.json                
npm notice 73B    .prettierrc                 
npm notice 1.1kB  index.js                    
npm notice 11.5kB middy-secrets-0.2.1.tgz     
npm notice 2.2kB  README.md                   
npm notice 1.2kB  .idea/codeStyles/Project.xml
npm notice 301B   .idea/composerJson.xml      
npm notice 22.5kB .idea/dbnavigator.xml       
npm notice 281B   .idea/middy-secrets.iml     
npm notice 174B   .idea/misc.xml              
npm notice 278B   .idea/modules.xml           
npm notice 180B   .idea/vcs.xml               
npm notice 23.2kB .idea/workspace.xml         

$ echo /.idea/ > .npmignore
$ npm pack

npm notice 
npm notice 📦  middy-secrets@0.2.1
npm notice === Tarball Contents === 
npm notice 867B   package.json           
npm notice 73B    .prettierrc            
npm notice 1.1kB  index.js               
npm notice 21.6kB middy-secrets-0.2.1.tgz
npm notice 2.2kB  README.md              
```
