### ISSUE TITLE
Projects leak in ExternalIndexableSetContributor.CACHE

### ISSUE THREAD

**Issue by ibessonov** [hsz/idea-gitignore#553]
### Prerequisites

* [x] Plugin is in the latest version
* [X] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

ExternalIndexableSetContributor.CACHE contains disposed projects in memory dump. This causes memory leaks and increases GC time.

Problem was discovered while inspecting this issue: https://youtrack.jetbrains.com/issue/IDEA-192493

**Comment by hsz** [comment]
@ibessonov Thank you for creating this issue. I have no access to the linked ticket:

> You have no permissions to view this page

Anyway, I've reviewed the code and `ExternalIndexableSetContributor.invalidateCache(Project)` is invoked always when the `IgnoreManager` project component is disposed (which is disposed when project is disposed).

**Comment by ibessonov** [comment]
Hi @hsz, I see invalidation in IgnoreManager, but at the same time I see disposed projects in CACHE map in ExternalIndexableSetContributor. I'm confused to be honest. You can investigate this dump: 
ftp://ftp.intellij.net/.uploads/damien-sorel-dump-and-logs-2018-06-29.zip, you'll find disposed IgnoreManager objects with disposed projects but valid cache.

Can it be that ExternalIndexableSetContributor#getAdditionalFiles is invoked after disposal? It would create empty values in CACHE.

**Comment by hsz** [comment]
@ibessonov I have checked the code again and it's almost impossible to have disposed projects in this map. Maybe there is some border case or issue in IDE SDK - who knows.
I did the additional check on project open/close - so if there will be new project opened or previous closed - it'll iterate through `CACHE` and remove all disposed entries from map.

**Comment by ibessonov** [comment]
Thank you!
Sorry that I didn't provide valid dump, I completely forgot that "ftp.intellij.net" is a write-only service for anonymous users. I wasn't able to reproduce this issue myself, it's clearly some border case. It probably occurs under high loads or in some rare data races.
