### ISSUE TITLE
Appears when a file is saved：Unable to save settings: Failed to save settings. Please restart PhpStorm 

### ISSUE THREAD

**Issue by catcoder** [hsz/idea-gitignore#555]
PHPStream use .ignore 2.6.2,
When i saving a file, a popup window showing:
![image](https://user-images.githubusercontent.com/834176/42979605-a720feb8-8c05-11e8-8a5d-c5449614b914.png)

**Comment by hsz** [comment]
@catcoder Can you please provide more details using the issue template?

**Comment by hsz** [comment]
Duplicate of #552
