### ISSUE TITLE
(merge bug) Generate without duplicates

### ISSUE THREAD

**Issue by bluelovers** [hsz/idea-gitignore#561]
### Prerequisites

* [x] Plugin is in the latest version

### Description

![2018-08-21-08-19-04-4](https://user-images.githubusercontent.com/167966/44373315-32378700-a51b-11e8-804c-99b6f433b93a.png)

![2018-08-21-08-19-24-5](https://user-images.githubusercontent.com/167966/44373318-35cb0e00-a51b-11e8-97e0-984530d684e8.png)

**Comment by hsz** [comment]
@bluelovers Thanks for the report!
Fixed and released with v3.1.1
