### ISSUE TITLE
Incompatible with latest version of Pycharm

### ISSUE THREAD

**Issue by Baneeishaque** [hsz/idea-gitignore#562]
### Prerequisites
* [X] Plugin is in the latest version
* [X] Issue was not reported yet

### Description
Plugin is incompatible with latest version of Pycharm.

### Steps to Reproduce
1. Download plugin zip file from Jetbrain's Plugin repository.
2. Choose Install plugin from Disk option.
3. Choose downloaded zip file and apply changes.

**Expected behavior:**
Plugin installation success.

**Actual behavior:** 
Error message dialogue - plugin is incompatible.

### Versions
**Plugin:** 
`3.0.0.141`

**IDE:** 
`Pycharm 2018.2`

**OS:** 
`Win7 64 bit`

**Comment by hsz** [comment]
@Baneeishaque  `3.0.0.141` version refer to the old IntelliJ SDK. You should update plugin to the newer version - `3.0.0.182` in case of `2018.2`

**Comment by magneticflux-** [comment]
@hsz This is still a problem with `183`, since there is no publication for it. This results in the plugin downgrading to `2.6.2`. Would it be possible to eliminate the upper bound for the highest compatibility layer so it can at least attempt to work on newer IDE versions?
