### ISSUE TITLE
Entries for existing archives *.7z, *.egg, etc, are marked as covered by */

### ISSUE THREAD

**Issue by AndrewUshakov** [hsz/idea-gitignore#565]
### Prerequisites

* [X] Plugin is in the latest version
* [X ] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

False positive...

### Steps to Reproduce

1. Add to directory any archive, say 7z-file.
2. Add .gitignore file like:
```
*/
*.7z
```
3. Open .gitignore in Pycharm.

**Expected behavior:**

No errors.

**Actual behavior:**
 
line with *.7z in the .gitignore file will be highlighted with message '*.7z' is covered by '*/'.  7z-file will be shown in the project pane as ignored. If remove this line from .gitignore, 7z-file in the project view will be untracked. So the problem is with the visualization of .gitignore file only.

**Reproduces how often:** 

100%

### Versions

**Plugin:** 
```
v3.0.0.182
```
**IDE:** 
```
Pycharm 2018.3 EAP 7
```
**OS:** 

```
Windows 7.1 64 bit
```

**Comment by hsz** [comment]
@AndrewUshakov Thank you for creating this issue. It's fixed and will be released with v3.1.0

**Comment by hsz** [comment]
Fixed and released with v3.1.1
