### ISSUE TITLE
Default global excludesfile is not recognised

### ISSUE THREAD

**Issue by canni** [hsz/idea-gitignore#574]
GIT has a default value for excludesfile global option, usually users create files like `~/.git_globalignore` but it is enough to create `~/.config/git/ignore` instead as it's a default for `excludesfile`
( https://stackoverflow.com/questions/7335420/global-git-ignore/22885996#22885996 )

.ignore plugin currently does not recognise exclusions saved in this file, even through git cmonnadmline API is using it.

**Comment by hsz** [comment]
Thanks for the ticket! It's implemented and will be available in v3.1.2
