### ISSUE TITLE
Gitkeep

### ISSUE THREAD

**Issue by longnguyen2306** [hsz/idea-gitignore#575]
### Prerequisites

* [ ] Plugin is in the latest version
* [ x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

How about a feature to add a .gitkeep? That should be simple to implement

**Comment by hsz** [comment]
Hi @longnguyen2306 
Thanks for asking!

Unfortunatelly `.gitkeep` is not in the scope of this plugin. Those files are rather a placeholder for tracking empty directories in GIT repositories.

> .gitkeep isn’t documented, because it’s not a feature of Git.
> Git cannot add a completely empty directory. People who want to track empty directories in Git have created the convention of putting files called .gitkeep in these directories. The file could be called anything; Git assigns no special significance to this name.

ref: https://stackoverflow.com/questions/7229885/what-are-the-differences-between-gitignore-and-gitkeep
