### ISSUE TITLE
Please add .nuxtignore to the list

### ISSUE THREAD

**Issue by koresar** [hsz/idea-gitignore#576]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet

### Description

Here is the new feature of the Nuxt.js framework.
https://nuxtjs.org/api/configuration-ignore#-nuxtignore

TL;DR: the `.nuxtignore` file format is identical to `.gitignore` one.

### Steps to Reproduce

1. Install
2. Check if syntax is highlighted in `.nuxtignore` file

**Expected behavior:**

Syntax highlight present

**Actual behavior:** 

Not recognised by the plugin by default.

### Versions

**Plugin:** 

Any

**IDE:** 

Any

**OS:** 

Any

**Comment by hsz** [comment]
Released with v3.1.1
