### ISSUE TITLE
Plugin shows incorrect information

### ISSUE THREAD

**Issue by benfreke** [hsz/idea-gitignore#579]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [ ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

The plugin is over-riding the Git ignore data or getting it wrong. Files that should be tracked are showing as ignored in the IDE when this plugin is enabled.

### Steps to Reproduce

1. Create a new project 
1. Create a directory, `parent`
1. Create a subdirectory under `parent`, `notignored`
1. Create a subdirectory under notignored, `subdirectory`
1. Put a file called `test.txt` in both `notignored` and `subdirectory`
1. Put the following codeblock in `.gitignore` in the `parent` directory

```bash
# Exclude everything
*
!.gitignore

# Whitelist include
!notignored
!notignored/**

```

**Expected behavior:**

The plugin should show the correct ignored information as per Git

**Actual behavior:** 

Files that are not ignored by Git are showing as ignored in the Project view AND in the banner when editing the files.

Turning the plugin off restores the expected behaviour. Since I need accurate information in the files more than I need the auto-creation, I've disabled the plugin.

**Reproduces how often:** 

100% of the time

### Versions

**Plugin:** 

`v2.6.2`

**IDE:** 

`PhpStorm 2019.1`

**OS:** 

Mac 10.14.4

### Additional Information

Screenshot showing this in action.

![gitignore-plugin-error](https://user-images.githubusercontent.com/1715284/55921973-83c78a00-5c42-11e9-80b8-a4f240657a0a.png)

edit 1: Fixed the checkbox display

**Comment by dailytabs** [comment]
![image](https://user-images.githubusercontent.com/1219653/57586144-84607400-74bf-11e9-829f-ba7fae5e89b1.png)

![image](https://user-images.githubusercontent.com/1219653/57586149-9510ea00-74bf-11e9-9102-4bc15275fc6f.png)

The "not"s seem to not work.

**Comment by hsz** [comment]
@benfreke Thank you for this report! It appeared that double star at the end didn't match _everything_ that comes after the previous pattern - but it should.
Problem is fixed and will be available in v3.1.1.

@dailytabs You're referring to the very different thing. Anyway, this feature has been removed with upcoming release: https://github.com/hsz/idea-gitignore/issues/486#issuecomment-490740469

**Comment by hsz** [comment]
Fixed and released with v3.1.1

**Comment by SkylerLS** [comment]
@hsz I'm on 3.1.1.191 just downloaded maybe 15 mins ago and PhpStorm thinks everything is ignored inside `/src`.

Is this the same or a different problem?
![Screen Shot 2019-05-13 at 12 18 05 PM](https://user-images.githubusercontent.com/21369525/57637367-4031aa00-7579-11e9-8d37-34da661e3b1c.png)

**Comment by hsz** [comment]
@SkylerLS That's a plot twist. Can you please share your .gitignore?

**Comment by SkylerLS** [comment]
Heh.

Sure. The top-level .gitignore is as follows:
```
.idea
.idea.bak
.env
docker/.volumes
**/secrets/*.yaml
infection-log.txt
```

The .gitignore inside `/src` is
```
/public/hot
/public/storage
/storage
/vendor
/.idea
/.env
/_ide_helper.php
```

Then some others in deeper layers too.

**Comment by hsz** [comment]
@SkylerLS I've created .gitignore files in the same way, but it behaves correctly and doesn't mark all of the content with gray.

Let's try with:
- adding empty lines in every .gitignore file and manually save with Ctrl+S
- File > Invalidate & Restart

**Comment by SkylerLS** [comment]
It was looking for a moment like it would work while the index was being rebuilt. But it didn't work.

**Comment by hsz** [comment]
@SkylerLS van you please prepare a minimal project example that can reproduce this behaviour?

**Comment by SkylerLS** [comment]
I'll update here when I can find the time to do that. Likely Wednesday or Thursday of this week.

**Comment by hsz** [comment]
All right, thanks n
Let's create a new ticket for that then.

**Comment by benfreke** [comment]
I just wanted to comment and say that my original issue is solved with the latest release. Thanks for the fix!
