### ISSUE TITLE
Idea 14 freezing after right click in *.gitignore

### ISSUE THREAD

**Issue by happylynx** [hsz/idea-gitignore#73]
Idea stops responding (responds really slowly, also other window system related operations slows down) and fully utilize one CPU core after right click in *.gitignore file managed by your plugin. No context menu is show.

Environment:
* .gitignore .hgignore .npmignore .dockerignore v0.8
* Idea 14.0.2
* OpenJDK Runtime Environment (fedora-2.5.3.3.fc20-x86_64 u71-b14)
* Fedora 20 x64

**Comment by hsz** [comment]
@happylynx Can you confirm if this issue still appears in `v0.8,1` ?
