### ISSUE TITLE
Feature request: chefignore support

### ISSUE THREAD

**Issue by Maks3w** [hsz/idea-gitignore#75]
> Chef now uses a single chefignore file, placed in the root of your cookbook repository, to determine which files to ignore when uploading cookbooks. chefignore files use Ruby’s File.fnmatch under the hood, so the syntax is similar to a shell glob—much more natural when dealing with file paths.

https://docs.chef.io/chef_repo.html#chefignore-files
https://www.chef.io/blog/2011/04/29/chef-0-10-preview-chefignore/
http://ruby-doc.org/core-2.2.0/File.html#M000001

**Comment by hsz** [comment]
@Maks3w Thanks for your message.

`Chef` support will be included in the next release. ;-)

**Comment by hsz** [comment]
@Maks3w Support introduced in release `v0.9`
