### ISSUE TITLE
Add "file ignored color"

### ISSUE THREAD

**Issue by Kendos-Kenlen** [hsz/idea-gitignore#79]
Hi,

Could it be to add the "file ignored color" to the files ignored by a .ignore, like when you add them to the "ignored files" VCS' settings option ? It a brown/yellow color who could help to know what - or not - is ignored in a project.

**Comment by hsz** [comment]
With new `v0.10` release there will be available this feature. All files matched by the ignore rules will be grayed in the Project View tree.

![image](https://cloud.githubusercontent.com/assets/108333/6373432/ed94a1ba-bd0a-11e4-8830-735a53885ab5.png)

**Comment by Kendos-Kenlen** [comment]
Hi,

The problem with the actual color is that it's already used by CLion to mark files who are not marked as source file in the CMakeLists.txt.

Could you use the "File Status -> ignored" color instead ? His hexa is : #848504.

**Comment by hsz** [comment]
@Kendos-Kenlen Ok, it will be available to change the default color in `Ignore files support` settings:

![image](https://cloud.githubusercontent.com/assets/108333/6410069/b146df04-be6b-11e4-9545-433e5230a280.png)
