### ISSUE TITLE
.hgignore should never consider 'syntax: glob' as "never used"

### ISSUE THREAD

**Issue by pepoluan** [hsz/idea-gitignore#82]
With version 0.9, the .ignore plugin considers the line `syntax: glob` as "never used".

Removing this entry (the suggested action) results in Mercurial mistakenly considering the glob entries as regex entries.

Therefore, `syntax: glob` must never be considered as "never used".

**Comment by hsz** [comment]
Hello @pepoluan 

Thank you for reporting it. It has been already fixed ant is waiting for release.
In next released version there will be available `syntax:` support and switching between regexp and glob syntax modes (regexp by default).

I have to finish one more feature and it'll be published tomorrow I think.
