### ISSUE TITLE
Wrong ignore indicator with nested ignore rules

### ISSUE THREAD

**Issue by manuakasam** [hsz/idea-gitignore#85]
Imagine the following directory structore

```
/foo
/foo/bar
/foo/bar/baz
/foo/ball
```

Assuming these contents for mutliple gitignores

**.gitignore**
```
/*
!foo/
```

**/foo/.gitignore**
```
/*
!.gitignore
!bar/
```

**/foo/bar.gitignore**
```
/*
!.gitignore
!baz/
```

Assuming the above ruling, all sub-directories under foo would be highlighted as **ignored**. Going by git itself however, the excluded rules match appropriately and files from `/foo/bar/` would be added to the index without any problems.

**Comment by serwizz** [comment]
Hi, I have same issue. I ignore some folders and file in `foo` folder. My .gitignore file is 
```
!/foo
/foo/*
!/foo/templates
/foo/templates/bad_template
```
but plugin painted all in `foo` folder in grey

**Comment by wlf10** [comment]
+1

**Comment by hsz** [comment]
Thank you guys for reporting it. I'll fix it soon.

**Comment by hsz** [comment]
Fixed with release `v1.0.1`.

Please confirm if everything is fine.

**Comment by manuakasam** [comment]
Hey Jakub,

first off: thanks for the really fast reply / fix (attempt).

As the word inclines however it appears that now the plugin is completely
broken as it doesn't color anything anymore :S
Tested on EAP, 8.0.2 and 8.0.3

It doesn't even work for top level files in a new project.

Jakub Chrzanowski <notifications@github.com> schrieb am Mi., 4. März 2015
um 00:00 Uhr:

**Comment by hsz** [comment]
Please verify if everything is fine with release `v1.1`.

**Comment by manuakasam** [comment]
Hey again Jakub,

the 1.1 release seems to have fixed the issue. Great work :)

/Sam

Jakub Chrzanowski <notifications@github.com> schrieb am Mo., 13. Apr. 2015
um 07:20 Uhr:
