### ISSUE TITLE
v1.0: "Cover entry" inspection and non-existing folders

### ISSUE THREAD

**Issue by frozenice** [hsz/idea-gitignore#88]
Just saw this inspection pop up after upgrading to 1.0:
![image](https://cloud.githubusercontent.com/assets/750902/6470288/ee3c1e90-c1e2-11e4-93e5-5382cf42e799.png)

If I create the dist folder, the inspection doesn't report a problem. Might also effect non-existing files, I haven't investigated further. :)

I'd expect the "Unused entry" inspection to fire here (which curiously has a severity of "Ignore.unusedentry" instead of "Warning" or "Error" in the settings, see [image](https://cloud.githubusercontent.com/assets/750902/6470392/bc31d97a-c1e3-11e4-931b-05459c19a372.png)).

**Comment by hsz** [comment]
@frozenice Thank you for reporting.

Can you click on the `dist/` entry with <kbd>Ctrl</kbd> pressed ?
I bet it is pointing to some folder inside the `node_modules` directory and that's why `node_modules` entry is covering something inside it.

**Comment by frozenice** [comment]
Ah, of course, you are right, I didn't think about inheritance/recursion. There are several dist folders deep inside node_modules (didn't know about the ctrl-click btw, nice!).

So I guess it's not really a bug, only confusing - though I don't know how that could be alleviated. Any word on the strangely named severity level?

**Comment by hsz** [comment]
`Ignore.unusedentry` was introduced to use different (gray) color. When using gitignore templates, by default the big part of them are not applied in the project (they are global) so marking them with red or yellow color is very annoying and distracting.

I will stay with this severity - I can rename it to `Unused Entry`.

**Comment by hsz** [comment]
Fixed with release `v1.0.1`.

Please confirm if everything is fine.

**Comment by frozenice** [comment]
Everything is fine. :+1:
