### ISSUE TITLE
V1.0.1

### ISSUE THREAD

**Issue by mathben** [hsz/idea-gitignore#89]
I update v1.0.0 to v1.0.1 and i got this error : 
com.intellij.diagnostic.PluginException: mobi/hsz/idea/gitignore/IgnoreManager$IgnoreCacheMap [Plugin: mobi.hsz.idea.gitignore]
I uninstall the plugin to continue my work.

Any idea?

**Comment by hsz** [comment]
What version of ide do you use?

**Comment by mathben** [comment]
clion 140-2310-6

**Comment by mathben** [comment]
Thanks you, it works now.
