### ISSUE TITLE
Expensive and often read-lock blocks common IDE actions

### ISSUE THREAD

**Issue by zolotov** [hsz/idea-gitignore#94]
Hi. [This piece of code](https://github.com/hsz/idea-gitignore/blob/master/src/mobi/hsz/idea/gitignore/IgnoreManager.java#L252) leads to freezing IDE. Please reimplement it, I can help you a little, but for now I can't compile your project – for some reason there are several classes missing.

This is brief explanation of freezing:

Every 200 ms you take read lock and run quite expensive and long operations (traversing file system and matching a butch of rexegp). However there are a lot of tasks in IDE that require write lock, and usually they are much more important than indexing ignored files. Indexing, saving IDE settings, refactorings, completion – all of these tasks require write action, they run on EDT and wait for your manager will finish  all its stuff, and all IDE is frozen for these moments.

So as a simple fix you can just use readlock for short and fast operations and only where read lock is really required, but not for whole indexing process every 200 ms.

As a recommenations:

For repeating operations it makes sense to use com.intellij.util.Alarm or com.intellij.util.ui.update.MergingUpdateQueue, it allows you to merge several tasks in one and avoid too often task launching, just make sure that you run them not on EDT (e.g. look at ApplicationImpl.executeOnPooledThread).

Also as I understand, all this construction was built just for caching isFileIgnored and isParentIgnored, right? In this case you can just remove whole indexing process and cache this values for each file separately using CacheValueProvider.

E.g.

```
    public boolean isFileIgnored(final VirtualFile file) {
        if (!isEnabled()) {
            return false;
        }
        return CachedValuesManager.getManager(myProject).getCachedValue(file, new CachedValueProvider<Boolean>() {
            @Nullable
            @Override
            public Result<Boolean> compute() {
                return Result.create(isParentIgnored(file) || expensiveCheckingThatFileIsIgnoredHere(file), file);
            }
        });
    }
    
    public boolean isParentIgnored(final VirtualFile file) {
        if (!isEnabled()) {
            return false;
        }
        return CachedValuesManager.getManager(myProject).getCachedValue(file, new CachedValueProvider<Boolean>() {
            @Nullable
            @Override
            public Result<Boolean> compute() {
                return Result.create(expensiveCheckingThatParentIsIgnoredHere(file), file);
            }
        });
    }
```

Results will be saved in files and will be invalidated on virtualFile changing. You can pass any `modification trackers/psiFiles/virtualFiles` as a parameter of `new Result()` and cache of particular file will be invalidated on changing passed objects.

**Comment by hsz** [comment]
@zolotov Thank you for this post.

About the code that uses `Timer` - isn't it working like: check every 200ms if `FileManager.isInitialized` - then stop the timer task and `runReadAction` once to create a cache map ?

**Comment by zolotov** [comment]
You're right, I've missed stopping part. Anyway I made this post not because I accidentally reviewed your code, users are complaining about performance in WebStorm and their thread dumps show that instead some useful, IDE is building cache of ignored files. So the issue is still actual: please avoid taking readLock in this part and reuse existing caching strategies.

**Comment by zolotov** [comment]
Nice, thanks.
Just couple notes:
1. it makes sense to invoke alarm.cancelAllRequests() just before adding new request, so it there are already several requests in queue they will be deleted and only last one will be actually executed.
2. read action still contains a lot of things inside. It's better to run many short read actions than single long read action. Please consider to run separate read action for FileTypeIndex.getFiles() method and for each cache.add(getIgnoreFile()). Of course this change requires profiling, don't do it blindly.

**Comment by hsz** [comment]
Please verify if everything is fine with release `v1.1`.

**Comment by zolotov** [comment]
@hsz looks good, thank you.

**Comment by hsz** [comment]
@zolotov Great, thank you for keeping an eye on it.
