### ISSUE TITLE
Lags(several seconds) while editing .ignore

### ISSUE THREAD

**Issue by krasa** [hsz/idea-gitignore#95]
whole project: 42 194 Files, 14 386 Folders (excluded and ignored /target has 37 643 Files, 13 964 Folders)

![image](https://cloud.githubusercontent.com/assets/1160875/6766733/96c31f68-d012-11e4-98f8-5eb20ec9723d.png)
![image](https://cloud.githubusercontent.com/assets/1160875/6766714/f33afe9c-d011-11e4-9549-bbfcfdcba4a4.png)
![image](https://cloud.githubusercontent.com/assets/1160875/6766722/3a8af716-d012-11e4-9559-8aa254b74a8f.png)

https://www.dropbox.com/s/xclle0gzpy4fg38/threadDumps-20150321-152824-IU-141.175.rar?dl=0

**Comment by hsz** [comment]
Please verify if everything is fine with release `v1.1`.
