### ISSUE TITLE
There is item "Add to null" in context menu

### ISSUE THREAD

**Issue by MadPitman** [hsz/idea-gitignore#96]
Hi!

The plugin adds item "Add to null" in context menu. Also, the item has help note "Add this file to null rules".

Thanks

![nullitem](https://cloud.githubusercontent.com/assets/960814/6823952/315e85f6-d2fe-11e4-874e-fd30d574410a.JPG)

**Comment by hsz** [comment]
Thank you for reporting - it's fixed and will be available in the next release.
