### ISSUE TITLE
New file .idea/dataSources.local.xml

### ISSUE THREAD

**Issue by knalli** [hsz/idea-gitignore#97]
I'm not sure if this is an addition of the latest 14.1 and/or Database Plugin. But a new datasource was added in the file `.idea/dataSources.local.xml`

I'd suggest to add this in the chapter of "JetBrains template > Sensitive or high-curn files"

**Comment by hsz** [comment]
Thank you for reporting.
Any changes related to the GitHub templates should be reported directly in their repository

https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore
