### ISSUE TITLE
Fossil Support

### ISSUE THREAD

**Issue by Jzar** [hsz/idea-gitignore#98]
I don't actually use Fossil, so I can't say this is super important to me.  However, Fossil has always looked like a very interesting project, and I know it has some very happy and dedicated users.  For the sake of completeness, I think it would be good to support Fossil here.

Here's the link to where Fossil describes how their "versionable settings" are setup:  http://fossil-scm.org/xfer/doc/trunk/www/settings.wiki

The important line is this:  "For example, to set the list of ignored files, create a .fossil-settings/ignore-glob file where each line contains a glob for ignored files."

**Comment by hsz** [comment]
Fossil has quite different logic - the rules are described in the `.fossil-settings/ignore-glob` file which is outside the project files scope.
All of the handled ignore files starts ignoring from the current working directory and cannot access other tree or parent scope.

**Comment by Jzar** [comment]
Interesting.  I was going to say, "This feature should be pretty easy!" and then I slapped myself, and left the analysis of whether it was possible or how easy to someone who actually knows something about it...  :D  Well, like I said, I don't think support for this is super important.

**Comment by hsz** [comment]
I'll not reject this feature request for now..
There is something simmilar to the rules defined out of the scope issue: Git allows to define the ignore rules common for all of the Git projects.

Reference: https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

I have a plan to handle this case too, so Fossil is quite simmilar to this one.

**Comment by hsz** [comment]
Introduced with release `v1.1`.
