### ISSUE TITLE
WS10 RC Memory Leak

### ISSUE THREAD

**Issue by red2678** [hsz/idea-gitignore#99]
Hi,

Just to say love your plugin!! However, according to JB support, this plugin could be causing a somewhat severe memory leak in WS10 RC (and early EAP versions). 

Here is my JB bug report and after their analysis of a memory dump, I was instructed to disable this plugin (and others). Are you guys aware of this issue? Plans to correct? I would love to re-enabled it. 

https://youtrack.jetbrains.com/issue/WEB-15627

Thanks!!

**Comment by hsz** [comment]
Please verify if everything is fine with release `v1.1`.

**Comment by red2678** [comment]
Seems to be working great again! Thanks so much. :+1:
